'use client';
import {useEffect,useMemo,useState} from 'react';
import {brandSetupScore} from '../lib/brand-setup.mjs';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,BookOpen,Brain,Check,ChevronDown,Globe2,ImageIcon,MessageSquare,Mic2,Palette,RefreshCw,Save,Sparkles,Target,WandSparkles} from 'lucide-react';

type Doc={source:string;text:string};
type Platform={id:string;enabled:boolean;language:string;bodyLinks:'url'|'handles';commentLinks:'on'|'off'};
type Profile={version:number;name:string;tone:string;styleNotes:string;interests:string[];platforms:Platform[];look:{primaryColor:string;accentColor:string;fontHeading:string;fontBody:string;watermark:string;assetIds:string[]};source:string;updatedAt:string|null};
type BrainData={owner:string;status:string;revision:string;vaultRevision:string;documents:Record<string,Doc>;samples:{path:string;status:string;text:string}[];assets:{id:string;width:number;height:number;reviewStatus:string}[];missing:string[];brainProfile:Profile;companyVaultProfile:Profile;persistence:{mode:string;verified:boolean;updatedAt?:string}};
const LANGUAGES=['English','Traditional Chinese (Hong Kong)','Traditional Chinese (Taiwan)','Cantonese (Hong Kong)'];
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const msg=(e:unknown)=>e instanceof Error?e.message:'暫時未能完成操作';

function Fold({icon,title,badge,children,open=false}:{icon:React.ReactNode;title:string;badge?:string;children?:React.ReactNode;open?:boolean}){return <details className="ommi-fold" open={open}><summary><span className="ommi-icon">{icon}</span><strong>{title}</strong>{badge&&<small>{badge}</small>}<ChevronDown size={16}/></summary>{children&&<div className="ommi-fold-body">{children}</div>}</details>}

export default function BrandBrain({tab,token}:{tab:string;token:string}){
 const active=['voice','look','sources','progress'].includes(tab)?tab:'voice';
 const [data,setData]=useState<BrainData|null>(null),[profile,setProfile]=useState<Profile|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[topic,setTopic]=useState('');
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');fetch('/api/brain',{signal:c.signal,cache:'no-store',headers:token?{Authorization:'Bearer '+token}:{}}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setProfile(copy(d.brainProfile));}).catch(e=>{if(e.name!=='AbortError'){setData(null);setProfile(null);setError(msg(e));}}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[refresh,token]);
 const dirty=useMemo(()=>!!data&&!!profile&&JSON.stringify(profile)!==JSON.stringify(data.brainProfile),[data,profile]);
 const configured=!!data&&data.status!=='unconfigured';
 const score=brandSetupScore(profile,{configured,verified:data?.persistence.verified,dirty});

 function patch(next:Partial<Profile>){setProfile(p=>p?{...p,...next}:p);setNotice('');}
 function patchPlatform(id:string,next:Partial<Platform>){setProfile(p=>p?{...p,platforms:p.platforms.map(row=>row.id===id?{...row,...next}:row)}:p);setNotice('');}
 async function save(){if(!profile||!token)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/brain',{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({profile})});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setProfile(copy(d.brainProfile));setNotice('Saved to Supabase and read back ✓');}catch(e){setError(msg(e));}finally{setBusy(false);}}
 function addTopic(){const value=topic.trim();if(!profile||!value||profile.interests.includes(value))return;patch({interests:[...profile.interests,value].slice(0,24)});setTopic('');}
 if(busy&&!data)return <div className="ommi-loading" role="status"><RefreshCw className="spin"/>Loading Ommi Brain…</div>;
 if(error&&!data)return <div className="error" role="alert">{error}</div>;
 if(!data||!profile)return null;
 return <div className="ommi-page">
  <header className="ommi-hero"><p>OMMI BRAIN</p><h1>Teach Ommi what sounds like you</h1><span>Shape the voice, visual taste, durable memory, and learning loop used across your content workflows.</span></header>
  <section className="ommi-guide"><BookOpen size={18}/><div><small>PAGE GUIDE · TEACH 1/5</small><strong>Let me learn what sounds unmistakably like you.</strong></div><button className="quiet" disabled>Open guide <ChevronDown size={14}/></button></section>
  <section className="ommi-setup"><Brain size={26}/><div><span><strong>Agent setup</strong> <b>{score}/7</b> {!configured&&<small>尚未設定 · 模板預設值不計進度</small>}</span><div className="ommi-progress"><i style={{width:`${score/7*100}%`}}/></div></div><Link className="button" href={score<7?'/voice':'/feed'}>{score<7?'Continue setup':'Use in Feed'} <ArrowRight size={15}/></Link><button className="quiet" disabled>Details <ChevronDown size={14}/></button></section>
  <Fold icon={<Target size={17}/>} title="Where your voice shows up" badge="Everything you set here feeds the work Ommi does for you."><div className="ommi-impact"><span>Company Vault</span><ArrowRight/><span>Ommi Brain</span><ArrowRight/><span>Feed / Inspiration</span><ArrowRight/><span>Queue draft</span></div></Fold>
  <nav className="ommi-tabs" aria-label="Ommi Brain sections">{[['voice','Voice'],['look','Look']].map(([id,label])=><Link key={id} aria-current={active===id?'page':undefined} href={id==='voice'?'/voice':`/voice?tab=${id}`}>{label}{(id==='sources'||id==='progress')&&<small>WIP</small>}</Link>)}</nav>
  <div className="ommi-blurb-row"><p className="ommi-blurb">{active==='voice'?'How Ommi writes as you. Tone, replies, and per-platform rules.':active==='look'?'How your images look. Colours, fonts, reference photos and shot language.':active==='sources'?'What Ommi remembers, where it came from, and which workflows may use it.':'What Ommi has learned so far, and what changed after review.'}</p><span role="status"><i className={data.persistence.verified?'live-dot':'draft-dot'}/><strong>{!configured?'尚未連接自己的Vault':data.persistence.verified?'Supabase saved':'Company Vault draft'}</strong> · {data.revision}<button aria-label="Refresh Ommi Brain" disabled={busy} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={13}/></button></span></div>
  {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}

  {active==='voice'&&<div className="ommi-stack">
   <section className="ommi-action-card"><span className="ommi-icon purple"><Sparkles size={18}/></span><div><h3>Generate a persona</h3><p>Start from this student's Company Vault, then fine-tune the writing brain below.</p></div><button className="quiet" onClick={()=>{setProfile(copy(data.companyVaultProfile));setNotice('Company Vault profile loaded. Review it, then save.');}}>Use Company Vault</button></section>
   <section className="ommi-section"><div className="ommi-section-title"><span className="ommi-icon purple"><Mic2 size={18}/></span><div><h3>Learn My Voice</h3><p>Scan approved posts from connected accounts and fill only empty fields.</p></div><small>WIP · future unlock</small></div><div className="ommi-scan-list">{['X','Instagram','Threads'].map(p=><label key={p}><input type="checkbox" checked readOnly/><span>{p}</span><small>Uses verified account samples</small></label>)}</div><button className="button ommi-wide" disabled>Scan my accounts · locked</button></section>
   <section className="ommi-section"><div className="ommi-section-title"><span className="ommi-icon purple"><WandSparkles size={18}/></span><div><h3>Writing Identity</h3><p>Define the writing personality Ommi uses for every post draft.</p></div></div><div className="ommi-form-grid"><label>Agent Profile Name<input value={profile.name} maxLength={80} onChange={e=>patch({name:e.target.value})}/></label><label>Tone<input value={profile.tone} maxLength={240} onChange={e=>patch({tone:e.target.value})}/></label></div><label>Style Notes<textarea value={profile.styleNotes} maxLength={8000} rows={8} onChange={e=>patch({styleNotes:e.target.value})}/></label></section>
   <Fold icon={<MessageSquare size={17}/>} title="How I Engage" badge="Replies · WIP Lesson 6"><p>Reply tone, tactics and examples remain visible for the later Engage workflow.</p></Fold>
   <Fold icon={<WandSparkles size={17}/>} title="Reply Prompt" badge="AI rules · WIP Lesson 6"><p>The editable reply agent prompt unlocks with Engage and review controls.</p></Fold>
   <section className="ommi-section"><div className="ommi-section-title"><span className="ommi-icon purple"><Target size={18}/></span><div><h3>Agent Topic Interests</h3><p>Topics that shape Feed relevance and Inspiration source picks.</p></div><small>{profile.interests.length} selected</small></div><div className="topic-chips">{profile.interests.map(value=><button key={value} aria-label={`Remove ${value}`} onClick={()=>patch({interests:profile.interests.filter(v=>v!==value)})}>{value} ×</button>)}</div><div className="topic-add"><input aria-label="New topic interest" value={topic} maxLength={60} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addTopic();}}} placeholder="e.g. AI agents"/><button className="quiet" onClick={addTopic}>Add topic</button></div></section>
   <section className="ommi-section"><div className="ommi-section-title"><span className="ommi-icon purple"><Globe2 size={18}/></span><div><h3>Platform Output Language</h3><p>Choose where Ommi writes, the language, and how source links are handled.</p></div></div><div className="platform-settings">{profile.platforms.map(row=><div key={row.id} className={!row.enabled?'disabled-row':''}><label className="platform-name"><input type="checkbox" checked={row.enabled} onChange={e=>patchPlatform(row.id,{enabled:e.target.checked})}/><strong>{row.id}</strong></label><select aria-label={`${row.id} body links`} value={row.bodyLinks} onChange={e=>patchPlatform(row.id,{bodyLinks:e.target.value as Platform['bodyLinks']})}><option value="handles">Body: @handles</option><option value="url">Body: source URL</option></select><select aria-label={`${row.id} comment links`} value={row.commentLinks} onChange={e=>patchPlatform(row.id,{commentLinks:e.target.value as Platform['commentLinks']})}><option value="off">Comment: links off</option><option value="on">Comment: links on</option></select><select aria-label={`${row.id} language`} value={row.language} onChange={e=>patchPlatform(row.id,{language:e.target.value})}>{LANGUAGES.map(l=><option key={l}>{l}</option>)}</select></div>)}</div></section>
  </div>}

  {active==='look'&&<div className="ommi-stack"><section className="ommi-action-card"><span className="ommi-icon purple"><Palette size={18}/></span><div><h3>Visual Identity</h3><p>Define how Ommi generates images—brand kit, references and prompt style.</p></div></section><section className="ommi-section"><div className="ommi-section-title"><span className="ommi-icon purple"><ImageIcon size={18}/></span><div><h3>Brand Kit</h3><p>These settings become the default for generated visual content.</p></div></div><div className="ommi-look-grid"><label>Primary colour<span className="color-field"><input type="color" value={profile.look.primaryColor} onChange={e=>patch({look:{...profile.look,primaryColor:e.target.value}})}/><code>{profile.look.primaryColor}</code></span></label><label>Accent colour<span className="color-field"><input type="color" value={profile.look.accentColor} onChange={e=>patch({look:{...profile.look,accentColor:e.target.value}})}/><code>{profile.look.accentColor}</code></span></label><label>Headline font<input value={profile.look.fontHeading} onChange={e=>patch({look:{...profile.look,fontHeading:e.target.value}})}/></label><label>Body font<input value={profile.look.fontBody} onChange={e=>patch({look:{...profile.look,fontBody:e.target.value}})}/></label></div><label>Brand watermark <small>optional</small><input value={profile.look.watermark} maxLength={100} onChange={e=>patch({look:{...profile.look,watermark:e.target.value}})} placeholder="@yourbrand"/></label><h4>Design References <small>{data.assets.length} / 6</small></h4><p>Company Vault assets used as visual evidence. Candidate status is preserved.</p><div className="ommi-reference-grid">{data.assets.slice(0,6).map(a=><figure key={a.id}><Image unoptimized src={`/api/brand/asset?id=${encodeURIComponent(a.id)}`} alt={`${a.id} design reference`} width={a.width} height={a.height} sizes="(max-width: 700px) 45vw, 160px"/><figcaption>{a.id}<small>{a.reviewStatus}</small></figcaption></figure>)}</div><Fold icon={<WandSparkles size={16}/>} title="Advanced Image Prompt" badge="WIP"><p>Low-level image prompt controls remain locked until the image workflow is taught.</p></Fold><div className="ommi-test"><div><strong>Test Preview</strong><p>Generate one sample image to verify the current Brand Kit.</p></div><button className="quiet" disabled>Generate Test Image · WIP</button></div></section></div>}

  {(active==='sources'||active==='progress')&&<section className="ommi-locked"><span className="ommi-icon purple">{active==='sources'?<Brain size={20}/>:<Target size={20}/>}</span><h2>{active==='sources'?'Memory':'Progress'} is ready to unlock later</h2><p>{active==='sources'?'This will show what Ommi remembers, its source, and which workflow may use it.':'This will show approved learning, evidence and review history. Nothing is learned automatically yet.'}</p><span>WIP 🚧 Lesson 6+</span></section>}

  {(active==='voice'||active==='look')&&<footer className="ommi-save"><div>{dirty?<><i/>Unsaved changes</>:data.persistence.verified?<><Check size={15}/>Saved and verified in Supabase</>:<>請先連接自己的Vault，再確認及保存品牌設定</>}</div>{!token?<Link className="quiet" href="/connections">Sign in to save</Link>:<button className="button" disabled={!configured||busy||(!dirty&&data.persistence.verified)} onClick={save}><Save size={15}/>{busy?'Saving…':'Save Ommi Brain'}</button>}</footer>}
 </div>;
}
