'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';
export default function CloudDraftQueue({token}:{token:string}){
 const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[tab,setTab]=useState('draft'),[filter,setFilter]=useState('All');
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setItems([]);if(!token){setLoading(false);return;}fetch('/api/content?scope=cloud',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[token,refresh]);
 const entries=items.flatMap(record=>(record.revisions.at(-1)?.outputs||[]).map((output:any)=>({record,output,state:record.queue?.[output.platform]||{status:'draft'}})));
 const shown=entries.filter(e=>e.state.status===tab&&(filter==='All'||e.output.platform===filter)).sort((a,b)=>tab==='scheduled'?String(a.state.scheduledAt).localeCompare(String(b.state.scheduledAt)):String(b.record.createdAt).localeCompare(String(a.record.createdAt)));
 return <section className="panel"><div className="section-heading"><div><h2>Queue</h2><p>所有平台文案自動保存到這裡，再編輯或安排時間。</p></div><Link className="button" href="/creator-studio">Create a post</Link></div><p className="small-copy">今堂只保存草稿及排期；社交帳戶／發布API下一堂接駁。到期仍會保留為待發布，唔會自動出帖。</p><div className="card-actions" style={{flexWrap:'wrap',marginBottom:24}}>{['draft','scheduled'].map(t=><button key={t} className={tab===t?'button':'quiet'} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='draft'?'Drafts':'Scheduled'} ({entries.filter(e=>e.state.status===t).length})</button>)}<label>平台 <select value={filter} onChange={e=>setFilter(e.target.value)}>{['All',...new Set(entries.map(e=>e.output.platform))].map(p=><option key={p}>{p}</option>)}</select></label><button className="quiet" onClick={()=>setRefresh(v=>v+1)}>重新讀取</button></div>{!token?<p>請先到<Link href="/connections">Connections登入</Link>。</p>:loading?<p role="status">讀取草稿…</p>:error?<p role="alert">{error}</p>:shown.length?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,340px),1fr))',gap:20,alignItems:'start'}}>{shown.map(({record,output,state})=><QueueCard key={record.id+output.platform+record.version} {...{record,output,state,token}} onSave={saved=>setItems(v=>v.map(r=>r.id===saved.id?saved:r))}/>)}</div>:<p>{tab==='draft'?'未有草稿。生成內容後會自動出現。':'未有排期。喺Drafts選一篇，設定日期及時間。'}</p>}</section>;
}
function QueueCard({record,output,state,token,onSave}:{record:any;output:any;state:any;token:string;onSave:(r:any)=>void}){
 const [editing,setEditing]=useState(false),[body,setBody]=useState(output.body),[title,setTitle]=useState(output.title||''),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 async function save(action:string){if(busy)return;setBusy(true);setError('');try{const time=date?new Date(date):null;if(action==='schedule'&&(!time||!Number.isFinite(time.getTime())))throw Error('請選日期及時間');const r=await fetch('/api/content',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action,id:record.id,expectedVersion:record.version,platform:output.platform,body,title,scheduledAt:time?.toISOString(),timeZone:zone})});const d=await r.json();if(!r.ok)throw Error(d.error);onSave(d);}catch(e){setError(e instanceof Error?e.message:'保存失敗');}finally{setBusy(false);}}
 return <article className="panel" style={{margin:0,minWidth:0}}><div className="section-heading"><strong>{output.platform}</strong><span className="tag">{state.status==='scheduled'?'Scheduled':'Draft'}</span></div>{state.scheduledAt&&<p><strong>{new Intl.DateTimeFormat('zh-HK',{dateStyle:'medium',timeStyle:'short',timeZone:state.timeZone}).format(new Date(state.scheduledAt))}</strong><br/><small>{state.timeZone} · {Date.parse(state.scheduledAt)<Date.now()?'已到期，待發布':'已安排，未發布'}</small></p>}{editing?<><label>標題<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>文案<textarea rows={10} value={body} onChange={e=>setBody(e.target.value)}/></label><p className="small-copy">修改文案會取消原排期，保存為草稿。</p><button className="button" disabled={busy} onClick={()=>void save('queueEdit')}>保存文案</button><button className="quiet" disabled={busy} onClick={()=>setEditing(false)}>取消</button></>:<>{record.images?.[output.platform]?.signedUrl&&<img src={record.images[output.platform].signedUrl} alt={output.platform+'配圖'} style={{width:'100%',maxHeight:420,objectFit:'contain'}}/>}<h3>{output.title}</h3><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{output.body}</p><button className="quiet" disabled={busy} onClick={()=>setEditing(true)}>編輯</button></>}<p className="small-copy">{record.brand?.owner} · v{record.version} · {record.model}</p>{record.brief?.source?.url&&<a href={record.brief.source.url} target="_blank" rel="noopener noreferrer">原始來源 ↗</a>}<details style={{marginTop:16}}><summary>{state.status==='scheduled'?'更改排期':'安排時間'}</summary><label>日期及時間（{zone}）<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="button" disabled={busy||!date||editing} onClick={()=>void save('schedule')}>保存排期</button></details>{state.status==='scheduled'&&<button className="quiet" disabled={busy} onClick={()=>void save('unschedule')}>取消排期 → Draft</button>}{busy&&<p role="status">保存中…</p>}{error&&<p role="alert">{error}</p>}</article>;
}
