'use client';
// Queue · 三欄（contracts/queue-columns.md）。出街只有一條路：呢度。
import {useEffect,useState} from 'react';import Link from 'next/link';
type Card={card_id:string;source_id:string;platform:string;title:string;content:string;content_hash:string;previous_hash?:string;attachment_ids:string[];attachments:{id:string;url:string;kind:string;mode?:string}[];publish_status:string;approval_hash:string;approval_valid:boolean;publish_route:string;scheduled_at:string|null;time_zone:string|null;submitted_id:string|null;published_id:string|null;public_url:string|null;verified_at:string|null;column:string;source?:{title:string;url:string;mode:string};events:any[];model?:string};
const COLS=[['draft','DRAFT'],['scheduled','SCHEDULED'],['published','PUBLISHED']] as const;
const fmt=(iso:string|null,tz?:string|null)=>iso?new Intl.DateTimeFormat('zh-HK',{dateStyle:'medium',timeStyle:'short',...(tz?{timeZone:tz}:{})}).format(new Date(iso)):'—';
export default function CloudDraftQueue({token}:{token:string}){
 const [cards,setCards]=useState<Card[]>([]),[legacy,setLegacy]=useState<any[]>([]),[routes,setRoutes]=useState<any>({}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tick,setTick]=useState(0),[col,setCol]=useState<'draft'|'scheduled'|'published'>('draft');
 useEffect(()=>{if(!token){setLoading(false);return;}const c=new AbortController();setLoading(true);setError('');
  Promise.all([fetch('/api/cards',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:c.signal}).then(r=>r.json()),fetch('/api/content?scope=cloud',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:c.signal}).then(r=>r.json())]).then(([a,b])=>{if(a.error)throw new Error(a.error);setCards(a.cards);setRoutes(a.routes||{});setLegacy(b.items||[]);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[token,tick]);
 const counts={draft:cards.filter(c=>c.column==='draft').length,scheduled:cards.filter(c=>c.column==='scheduled').length,published:cards.filter(c=>c.column==='published').length};
 const shown=cards.filter(c=>c.column===col).sort((a,b)=>col==='scheduled'?String(a.scheduled_at).localeCompare(String(b.scheduled_at)):String(b.events?.at(-1)?.at||'').localeCompare(String(a.events?.at(-1)?.at||'')));
 return <section className="panel"><div className="section-heading"><div><h2>Queue</h2><p>三欄：DRAFT（draft／approved）· SCHEDULED（scheduled／submitted／unknown）· PUBLISHED（verify 查到先入）。</p></div><Link className="button" href="/composer">Composer</Link></div>
  <p className="small-copy">Scheduled 只係已安排。UNKNOWN 留喺 SCHEDULED，唯一下一步係「再查一次」，唔係再發。</p>
  <div className="card-actions" style={{flexWrap:'wrap',marginBottom:24}}>{COLS.map(([k,label])=><button key={k} className={col===k?'button':'quiet'} aria-pressed={col===k} onClick={()=>setCol(k)}>{label} ({counts[k]})</button>)}<button className="quiet" onClick={()=>setTick(v=>v+1)}>重新讀取</button></div>
  {!token?<p>請先到<Link href="/connections">Connections登入</Link>。</p>:loading?<p role="status">讀取草稿…</p>:error?<p role="alert">{error}</p>:shown.length?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,340px),1fr))',gap:20,alignItems:'start'}}>{shown.map(c=><QueueCard key={c.card_id+c.content_hash+c.publish_status} card={c} token={token} routes={routes} onChange={()=>setTick(v=>v+1)}/>)}</div>:<p>{col==='draft'?'未有卡。去 Composer 撳「我把聲」。':col==='scheduled'?'未有排期。':'未有 published 卡——出咗街而且 verify 查到先會入呢欄。'}</p>}
  {legacy.length>0&&<details style={{marginTop:24}}><summary>上堂（第五堂）嘅草稿 {legacy.length} 份 — 舊格式，只可以排期／取消</summary><LegacyList items={legacy} token={token} onChange={()=>setTick(v=>v+1)}/></details>}
 </section>;
}
function QueueCard({card,token,routes,onChange}:{card:Card;token:string;routes:any;onChange:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(false),[body,setBody]=useState(card.content),[title,setTitle]=useState(card.title||''),[date,setDate]=useState(''),[pack,setPack]=useState<any>(null),[result,setResult]=useState<any>(null),[attachUrl,setAttachUrl]=useState('');
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 async function act(path:string,payload:any){if(busy)return null;setBusy(true);setError('');try{const r=await fetch(path,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({cardId:card.card_id,...payload})});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}catch(e){setError(e instanceof Error?e.message:'未完成');return null;}finally{setBusy(false);}}
 const s=card.publish_status;const status=s==='approved'?'已批準':s==='draft'?'未批準':s==='scheduled'?(card.approval_valid?'已安排 · 已批準':'已安排 · 未批準（runner 唔會發）'):s==='submitted'?'已送出':s==='unknown'?'UNKNOWN · 待查':'已出街';
 return <article className="panel" style={{margin:0,minWidth:0}}>
  <div className="section-heading"><strong>{card.platform}</strong><span className="tag" style={s==='unknown'?{background:'#ffe3b3'}:s==='published'?{background:'#d9f7e3'}:undefined}>{status}</span></div>
  <p className="small-copy">{card.source_id}{card.source?.mode==='DEMO'&&' · DEMO'} · hash <code>{card.content_hash}</code>{card.previous_hash&&<> ← <s>{card.previous_hash}</s></>} · route <code>{card.publish_route}</code>{card.attachment_ids?.length>0&&<> · 附件 {card.attachment_ids.length}</>}</p>
  {card.attachments?.[0]?.kind==='image'&&<p className="small-copy">🖼 {card.attachments[0].id}{card.attachments[0].mode==='DEMO'&&' (DEMO)'}</p>}
  {editing?<><label>標題<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>文案<textarea rows={8} value={body} onChange={e=>setBody(e.target.value)}/></label><p className="small-copy">改一個字，hash 就變，批準作廢。</p><button className="button" disabled={busy} onClick={async()=>{const d=await act('/api/cards',{action:'edit',content:body,title});if(d){setEditing(false);onChange();}}}>保存</button><button className="quiet" disabled={busy} onClick={()=>setEditing(false)}>取消</button></>
  :<><h3 style={{fontSize:16}}>{card.title}</h3><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{card.content}</p></>}
  {s==='published'&&<p><a href={card.public_url||'#'} target="_blank" rel="noopener noreferrer"><strong>公開連結 ↗</strong></a><br/><small>submitted {card.submitted_id} · published {card.published_id} · verified {fmt(card.verified_at)}</small></p>}
  {(s==='submitted'||s==='unknown')&&<p className="small-copy">submitted_id：{card.submitted_id||'—'} · published_id：{card.published_id||'—'} · public_url：{card.public_url||'查唔到'}<br/><button className="button" disabled={busy} onClick={async()=>{const d=await act('/api/publish',{action:'verify'});if(d){setResult(d.result);onChange();}}}>再查一次</button> <span className="muted">（唔好再發）</span></p>}
  {card.scheduled_at&&<p><strong>{fmt(card.scheduled_at,card.time_zone)}</strong> <small>{card.time_zone}</small></p>}
  {(s==='draft'||s==='approved')&&<div style={{display:'grid',gap:8,marginTop:8}}>
   {card.platform!=='newsletter'&&<label>路線 <select value={card.publish_route} disabled={busy} onChange={async e=>{const d=await act('/api/cards',{action:'route',route:e.target.value});if(d)onChange();}}><option value="unset">未揀</option>{card.platform==='threads'&&<option value="threads_direct">threads_direct（自己 token）{!routes.threads_direct&&' · 未設 token'}</option>}<option value="upload_post">upload_post{!routes.upload_post&&' · 未設 key'}</option></select></label>}
   <div className="card-actions" style={{flexWrap:'wrap'}}>
    <button className="quiet" disabled={busy} onClick={async()=>{const d=await act('/api/cards',{action:'dryrun'});if(d)setPack(d.pack);}}>Dry-run</button>
    {s==='draft'&&<button className="button" disabled={busy||!pack} title={!pack?'先 dry-run':''} onClick={async()=>{const d=await act('/api/cards',{action:'approve'});if(d){setPack(null);onChange();}}}>批準（我睇過預演）</button>}
    {s==='approved'&&<button className="button" disabled={busy} onClick={async()=>{if(!confirm('只發一次。發出後唔可以收返。繼續？'))return;const d=await act('/api/publish',{action:'publish'});if(d){setResult(d.result);onChange();}}}>只發一次</button>}
    <button className="quiet" disabled={busy||s==='approved'} onClick={()=>setEditing(true)}>編輯</button>
   </div>
   <details><summary>附件（圖）</summary><GeneratedImagePicker token={token} busy={busy} onPick={async taskId=>{const d=await act('/api/cards',{action:'attach',taskId});if(d)onChange();}}/><input placeholder="或者貼一個圖片 URL（fixture 用）" value={attachUrl} onChange={e=>setAttachUrl(e.target.value)}/><button className="quiet" disabled={busy||!attachUrl} onClick={async()=>{const d=await act('/api/cards',{action:'attach',attachment:{id:'img-'+Date.now().toString(36),url:attachUrl,kind:'image',mode:/example\.invalid|fixture/.test(attachUrl)?'DEMO':'LIVE'}});if(d){setAttachUrl('');onChange();}}}>附到卡（批準會失效）</button></details>
   <details><summary>排期</summary><label>日期及時間（{zone}）<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="button" disabled={busy||!date} onClick={async()=>{const d=await act('/api/cards',{action:'schedule',scheduledAt:new Date(date).toISOString(),timeZone:zone});if(d)onChange();}}>保存排期</button><p className="small-copy">Scheduled ≠ published。未批準嘅卡就算到時 runner 都唔會發。</p></details>
  </div>}
  {s==='scheduled'&&<button className="quiet" disabled={busy} onClick={async()=>{const d=await act('/api/cards',{action:'unschedule'});if(d)onChange();}}>取消排期 → {card.approval_valid?'approved':'draft'}</button>}
  {pack&&<details open style={{marginTop:8}}><summary>Dry-run 校對單 {pack.ok?'✓':'✗'}</summary><p className="small-copy">帳戶：{pack.target_account||'—'}<br/>路線：{pack.publish_route}<br/>hash：{pack.content_hash}<br/>附件：{pack.attachment_ids.length?pack.attachment_ids.join(', '):'冇'}<br/>idempotency：{pack.idempotency_key?.slice(0,16)}…<br/>公開後：{pack.what_happens_after}</p>{pack.problems.length>0&&<ul className="small-copy">{pack.problems.map((p:string)=><li key={p} style={{color:'#b00020'}}>{p}</li>)}</ul>}<p className="small-copy" style={{whiteSpace:'pre-wrap',borderTop:'1px solid #e9e7ee',paddingTop:6}}>{pack.full_text}</p><p className="small-copy"><em>{pack.note}</em></p></details>}
  {result&&<p className="small-copy" role="status" style={{padding:8,border:'1px solid #7C5CFF',borderRadius:8}}><strong>{result.status}</strong>{result.reason&&` · ${result.reason}`}<br/>submitted_id：{result.submitted_id||'—'}<br/>published_id：{result.published_id||'—'}<br/>public_url：{result.public_url?<a href={result.public_url} target="_blank" rel="noopener noreferrer">{result.public_url}</a>:'—'}{result.note&&<><br/>{result.note}</>}{result.error&&<><br/>error：{result.error}</>}</p>}
  {busy&&<p role="status">處理中…</p>}{error&&<p role="alert">{error}</p>}
  <details><summary className="small-copy">紀錄 {card.events?.length||0}</summary><ul className="small-copy">{(card.events||[]).slice(-8).map((e,i)=><li key={i}>{fmt(e.at)} · {e.action}{e.note?` · ${e.note}`:''}</li>)}</ul></details>
 </article>;
}
function GeneratedImagePicker({token,busy,onPick}:{token:string;busy:boolean;onPick:(taskId:string)=>void}){
 const [items,setItems]=useState<any[]>([]),[open,setOpen]=useState(false);
 useEffect(()=>{if(!open)return;fetch('/api/image',{headers:{Authorization:'Bearer '+token},cache:'no-store'}).then(r=>r.json()).then(d=>setItems(d.items||[])).catch(()=>setItems([]));},[open,token]);
 if(!open)return <button className="quiet" onClick={()=>setOpen(true)}>揀一張已生成嘅圖（Creator Studio）</button>;
 return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(96px,1fr))',gap:8,margin:'8px 0'}}>{items.length?items.map(it=><button key={it.taskId} className="quiet" disabled={busy} title={it.prompt?.slice(0,120)} style={{padding:4}} onClick={()=>onPick(it.taskId)}>{it.signedUrl?<img src={it.signedUrl} alt="" style={{width:'100%',aspectRatio:'1',objectFit:'cover',borderRadius:6}}/>:it.taskId.slice(0,8)}</button>):<span className="small-copy">未有已生成嘅圖——去 Creator Studio 用模板出一張（Step 19）。</span>}</div>;
}
function LegacyList({items,token,onChange}:{items:any[];token:string;onChange:()=>void}){
 const entries=items.flatMap(record=>(record.revisions.at(-1)?.outputs||[]).map((output:any)=>({record,output,state:record.queue?.[output.platform]||{status:'draft'}})));
 return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,340px),1fr))',gap:20,alignItems:'start',marginTop:12}}>{entries.map(({record,output,state})=><LegacyCard key={record.id+output.platform+record.version} {...{record,output,state,token}} onSave={onChange}/>)}</div>;
}
function LegacyCard({record,output,state,token,onSave}:{record:any;output:any;state:any;token:string;onSave:()=>void}){
 const [date,setDate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 async function save(action:string){if(busy)return;setBusy(true);setError('');try{const time=date?new Date(date):null;if(action==='schedule'&&(!time||!Number.isFinite(time.getTime())))throw Error('請選日期及時間');const r=await fetch('/api/content',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action,id:record.id,expectedVersion:record.version,platform:output.platform,scheduledAt:time?.toISOString(),timeZone:zone})});const d=await r.json();if(!r.ok)throw Error(d.error);onSave();}catch(e){setError(e instanceof Error?e.message:'保存失敗');}finally{setBusy(false);}}
 return <article className="panel" style={{margin:0,minWidth:0}}><div className="section-heading"><strong>{output.platform}</strong><span className="tag">{state.status==='scheduled'?'Scheduled':'Draft'} · v{record.version}</span></div>{state.scheduledAt&&<p><strong>{new Intl.DateTimeFormat('zh-HK',{dateStyle:'medium',timeStyle:'short',timeZone:state.timeZone}).format(new Date(state.scheduledAt))}</strong></p>}<h3 style={{fontSize:16}}>{output.title}</h3><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{output.body}</p><p className="small-copy">{record.model} · 舊格式（冇 content_hash，唔可以由 queue 出街；想出街去 Composer 重新排版）</p><details><summary>{state.status==='scheduled'?'更改排期':'安排時間'}</summary><label>日期及時間（{zone}）<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="button" disabled={busy||!date} onClick={()=>void save('schedule')}>保存排期</button></details>{state.status==='scheduled'&&<button className="quiet" disabled={busy} onClick={()=>void save('unschedule')}>取消排期 → Draft</button>}{error&&<p role="alert">{error}</p>}</article>;
}
