'use client';
import Link from 'next/link';
import TeacherWorkbench from './teacher-workbench';
import {useEffect,useState,useRef} from 'react';
import {WorkflowRail} from './workflow';
import {prepareBrief} from '../lib/brief.mjs';
import {ArrowRight,FileText,Image as ImageIcon,Link2,Search,Settings2,Sparkles,X} from 'lucide-react';
import ImageTemplateStudio from './image-template-studio';
import {parseComposerInput} from '../lib/composer-input.mjs';
type Row=Record<string,unknown>;
export function ContentCollection({rows,busy,error,select,inspect}:{rows:Row[];busy:boolean;error:string;select:(r:Row)=>void;inspect:(r:Row)=>void}){
 const [find,setFind]=useState('');const filtered=rows.filter(r=>String(r.caption||'').toLowerCase().includes(find.toLowerCase())||String(r.account||'').toLowerCase().includes(find.toLowerCase()));
 return <><WorkflowRail active="/collection"/><section className="panel"><div className="section-heading"><div><h2>Collection</h2><p>已保存嘅來源，揀一條帶入創作。呢度未啟用新增收藏或分類。</p></div><button disabled>＋ Add · WIP</button></div><div className="work-tabs"><span>已保存來源</span><button disabled>Images & screenshots · WIP</button><button disabled>Favourites · WIP</button></div><label className="card-search">搜尋本頁來源<input value={find} onChange={e=>setFind(e.target.value)} placeholder="帳號或內容…"/></label>{rows.some(r=>r.__demo)&&<p className="demo-banner">合成示範素材 · 不是真實 Supabase 記錄</p>}{busy?<p role="status">讀取來源…</p>:error?<div className="notice" role="alert">{error} <Link href="/connections">檢查 Supabase 連線</Link></div>:!rows.length?<div className="empty">未有可見來源。<Link href="/connections">檢查連線</Link></div>:<div className="source-cards">{filtered.map((r,i)=><article key={String(r.post_id||i)}><div className="source-excerpt">{String(r.caption||r.notes||'未有原文；可查看原始記錄。')}</div><h3>{String(r.account||r.platform||'已保存來源')}</h3><p className="small-copy">{String(r.platform||'')} · {String(r.content_type||'')}<br/>{String(r.post_id||'')}</p><div className="card-actions"><button className="quiet" onClick={()=>inspect(r)}>查看原始資料</button><button className="button" disabled={!r.caption} onClick={()=>select(r)}>Create from this →</button></div></article>)}</div>}</section></>;
}
export function ContentHome({showImage=true,source,text,setText,platforms,setPlatforms,clear,token}:{showImage?:boolean;source:Row|null;text:string;setText:(v:string)=>void;platforms:string[];setPlatforms:(v:string[])=>void;clear:()=>void;token:string}){
 const [brain,setBrain]=useState<{revision:string;owner:string}|null>(null);
 const [mode,setMode]=useState<'text'|'topic'>('text');
 const [settings,setSettings]=useState(false);const [recent,setRecent]=useState<any[]>([]),[recentError,setRecentError]=useState('');
 useEffect(()=>{const c=new AbortController();setRecent([]);setRecentError('');if(token)fetch('/api/content?scope=cloud',{headers:{Authorization:'Bearer '+token},signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setRecent(d.items);}).catch(e=>{if(e.name!=='AbortError')setRecentError(e.message);});return()=>c.abort();},[token]);
 const [readingLink,setReadingLink]=useState(false),[resolvedLink,setResolvedLink]=useState<any>(null);
 const [editOutputs,setEditOutputs]=useState<any[]|null>(null);
 async function saveEdit(){try{const r=await fetch('/api/content',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action:'edit',id:draft.id,expectedVersion:draft.version,outputs:editOutputs})});const value=await r.json();if(!r.ok)throw new Error(value.error);setDraft(value);setEditOutputs(null);}catch(e){setGenerationError(e instanceof Error?e.message:'修改未保存');}}
 const [pendingRequest,setPendingRequest]=useState('');
 const [generating,setGenerating]=useState(false),[generationError,setGenerationError]=useState(''),[draft,setDraft]=useState<any>(null);const inFlight=useRef(false),activeToken=useRef(token);
 useEffect(()=>{activeToken.current=token;setDraft(null);setGenerationError('');setPendingRequest(sessionStorage.getItem('personalos-text-request')||'');},[token]);
 async function generate(recover=false){if(inFlight.current)return;const startedToken=token;inFlight.current=true;setGenerating(true);setGenerationError('');setDraft(null);try{let sourceRequestIds:string[]=[];let content=text;const parsed=parseComposerInput(text);if(!recover&&!source&&parsed.urls.length){setReadingLink(true);const sources=[];for(const url of parsed.urls){const resolved=await fetch('/api/source',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await resolved.json();if(!resolved.ok)throw new Error(data.error);sourceRequestIds.push(data.sourceRequestId);sources.push(data.source);}setResolvedLink({title:sources.map(s=>s.title).join(' · '),text:sources.map(s=>s.text).join('\n\n')});content=parsed.opinion||'根據已讀取的來源，以Ommi Brain品牌語氣改寫，分清來源聲稱與自己的觀點，不虚構案例或數字。';setReadingLink(false);}const requestId=recover?pendingRequest:crypto.randomUUID();sessionStorage.setItem('personalos-text-request',requestId);setPendingRequest(requestId);const r=await fetch('/api/create',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(recover?{requestId,action:'recover'}:{requestId,text:content,platforms,postId:source?.post_id||null,sourceRequestIds})});const d=await r.json();if(activeToken.current!==startedToken)return;if(!r.ok){if(d.terminal){sessionStorage.removeItem('personalos-text-request');setPendingRequest('');}throw new Error(d.error+(d.draftId?' · 請求 '+d.draftId+'（請先核對，勿重複付費）':''));}sessionStorage.removeItem('personalos-text-request');setPendingRequest('');setDraft(d);setRecent(v=>[d,...v.filter(x=>x.id!==d.id)]);setBrain(d.brand);}catch(e){if(activeToken.current===startedToken)setGenerationError(e instanceof Error?e.message:'生成未完成');}finally{inFlight.current=false;setGenerating(false);setReadingLink(false);}}

 useEffect(()=>{const c=new AbortController();fetch('/api/brand',{signal:c.signal,headers:token?{Authorization:'Bearer '+token}:{}}).then(r=>r.ok?r.json():null).then(setBrain).catch(()=>{});return()=>c.abort();},[token]);
 function exportBrief(){const blob=new Blob([JSON.stringify(prepareBrief({source,input:text,platforms,brand:brain}),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='content-brief.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 let inputSources:string[]=[];try{inputSources=parseComposerInput(text).urls;}catch{}
 const ready=!!text.trim()&&!!platforms.length&&!!brain;
 return <div className="creator-home">
  <header className="creator-home-head"><div><span>OMMI CREATOR STUDIO</span><h1>Turn ideas into posts.</h1><p>貼X帖子連結、公開文章或文字，或者由 Feed／Inspiration 揀一個來源。</p></div><Link href="/voice">Ommi Brain <ArrowRight size={15}/></Link></header>
  <section className="creator-command" aria-labelledby="creator-command-title">
   <header><div><Sparkles size={19}/><div><h2 id="creator-command-title">你今日想講咩？</h2><p>{source?'來源已帶入，加入你嘅觀點再揀輸出平台。':'由一個真實來源或者你自己嘅想法開始。'}</p></div></div><button className="creator-settings-toggle" aria-expanded={settings} onClick={()=>setSettings(!settings)}><Settings2 size={16}/> 輸出設定</button></header>
   {source&&<div className="creator-source"><div><small>已帶入來源</small><strong>{String(source.account||source.platform||'已保存內容')}</strong><span>{String(source.post_id||'')}</span></div><button aria-label="清除已帶入來源" onClick={clear}><X size={16}/></button></div>}
   {!source&&inputSources.length>0&&<div className="creator-source"><strong>來源連結（{inputSources.length}）</strong><div>{inputSources.map(url=><p key={url} style={{overflowWrap:'anywhere'}}>{url}</p>)}<small>連結會先讀取及保存；其餘文字作為你的觀點。</small></div></div>}
   <div className="creator-input-card">
    <div className="creator-input-tabs" role="group" aria-label="輸入方式"><button className={mode==='text'?'active':''} aria-pressed={mode==='text'} onClick={()=>setMode('text')}><Link2 size={15}/> Link / text</button><button className={mode==='topic'?'active':''} aria-pressed={mode==='topic'} onClick={()=>setMode('topic')}><Search size={15}/> Find sources</button></div>
    <div className="creator-textarea"><span>{mode==='topic'?<Search size={20}/>:<FileText size={20}/>}</span><label className="sr-only" htmlFor="brief-input">{mode==='topic'?'想探索嘅主題':'連結或文字'}</label><textarea id="brief-input" value={text} onChange={e=>setText(e.target.value)} placeholder={mode==='topic'?'輸入你想探索嘅主題…':'貼上連結、文字，或者寫低你嘅觀點…'}/><Link href="/creator-studio#image-templates" title="前往參考圖與品牌模板" aria-label="前往參考圖與品牌模板"><ImageIcon size={18}/></Link></div>
    <p>{mode==='topic'?'搜尋來源功能稍後開放；目前可先到 Feed 或 Inspiration 揀來源。':'Ommi 會保留來源事實，再用你嘅品牌語氣重新組織。'}</p>
   </div>
   <div className={'creator-output-settings '+(settings?'open':'')}><div><strong>輸出平台</strong><span>同一個想法，按每個平台格式輸出。</span></div><div className="platform-choices" aria-label="輸出平台">{['Threads','Instagram','X','LinkedIn','Newsletter','Video Script'].map(p=><button key={p} className={platforms.includes(p)?'chosen':''} aria-pressed={platforms.includes(p)} onClick={()=>setPlatforms(platforms.includes(p)?platforms.filter(x=>x!==p):[...platforms,p])}>{p}</button>)}</div></div>
   <footer className="creator-command-footer"><div><span className={brain?'creator-ready':'creator-pending'}/><span>{brain?`${brain.owner} · Ommi Brain ${brain.revision}`:'正在讀取 Ommi Brain…'}</span></div><div><button className="quiet" disabled={!ready} onClick={exportBrief}>下載工作簡報</button><button className="button" disabled={mode==='topic'||!ready||!token||generating||!!pendingRequest||text.trim().length<10} onClick={()=>void generate()}>{mode==='topic'?'Find sources · WIP':readingLink?'讀取連結正文…':generating?'DeepSeek V4 Flash 改寫及保存中…':'Rewrite into posts'} <ArrowRight size={15}/></button></div></footer>
  </section>
  <section className="creator-entry-grid" aria-label="開始方法"><Link href="/feed"><FileText/><div><strong>由新聞開始</strong><span>Feed · RSS文章及正文</span></div><ArrowRight/></Link><Link href="/inspiration"><Search/><div><strong>由靈感開始</strong><span>Inspiration · 社交平台帖子</span></div><ArrowRight/></Link></section>
  <p className="small-copy">文字模型：deepseek-v4-flash（ToAPI） · 選定平台各一份 · 保存至Supabase，未發布。</p>
  {pendingRequest&&<button className="quiet" disabled={generating||!token} onClick={()=>void generate(true)}>讀回／恢復上次文字請求（不重新生成）</button>}
  {resolvedLink&&<section className="panel"><h3>已讀取來源：{resolvedLink.title}</h3><p>{resolvedLink.text.slice(0,300)}{resolvedLink.text.length>300?'…':''}</p><small>原文已保存到Supabase；改寫使用讀取到的內容。</small></section>}
  {generationError&&<p className="notice" role="alert">{generationError}</p>}
  {generating&&<p role="status">生成中，請勿重複點擊。完成後將核對Supabase保存結果。</p>}
  {draft&&<section className="panel"><h2>品牌草稿已加入Queue</h2><button className="quiet" onClick={()=>setEditOutputs(draft.revisions.at(-1).outputs.map((o:any)=>({...o})))}>修改本次草稿</button>{editOutputs&&<div>{editOutputs.map((o:any,i:number)=><label key={o.platform}>{o.platform}<textarea value={o.body} onChange={e=>setEditOutputs(v=>v!.map((x,n)=>n===i?{...x,body:e.target.value}:x))}/></label>)}<button className="button" onClick={()=>void saveEdit()}>保存修改版本</button></div>}<p className="success">Supabase已讀回 · {draft.model} · {draft.id}</p>{draft.revisions.at(-1).outputs.map((o:any)=><article key={o.platform}><h3>{o.platform} · {o.title}</h3><p className="brand-copy" style={{whiteSpace:'pre-wrap'}}>{o.body}</p></article>)}<p className="small-copy">ToAPI用量：{draft.usage?.total_tokens??'未知'} tokens · 文字與圖片共用ToAPI額度；實際費用待帳單核對。</p><Link href="/queue">到Queue管理草稿／排期 →</Link></section>}
  {showImage&&<ImageTemplateStudio key={token} token={token} text={text}/>}
  <section className="creator-drafts"><header><div><h2>Recent drafts</h2><p>完成改寫後，草稿會保留來源、品牌版本同平台。</p></div><Link href="/queue">View Queue <ArrowRight size={15}/></Link></header><div>{recentError?<p role="alert">{recentError}</p>:recent.length?recent.slice(0,3).map(r=><article className="panel" key={r.id}><strong>{r.revisions.at(-1).outputs.map((o:any)=>o.platform).join(' · ')}</strong><p>{r.model} · Supabase已保存</p><p className="small-copy">{r.id}</p><Link href="/queue">閱讀草稿 →</Link></article>):<span>{token?'未有已保存草稿':'登入後讀取已保存草稿'}</span>}<small>已自動加入Queue草稿；可編輯及保存排期，未連接發布API。</small></div></section>
  <details className="creator-course-map"><summary>課堂製作流程</summary><WorkflowRail active="/dashboard"/></details>
  <details className="creator-teacher-tools"><summary>老師進階測試工具</summary><TeacherWorkbench brief={()=>prepareBrief({source,input:text,platforms,brand:brain})}/></details>
 </div>;
}
