'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Image as ImageIcon,LoaderCircle,RefreshCw,Sparkles} from 'lucide-react';

type Generated={taskId:string;signedUrl:string;size:string;resolution:string;model:string;prompt:string;generatedAt:string;estimatedCredits:number;observedCredits?:number;storageVerified:boolean};
const ratios=[['1:1','Square'],['4:5','Portrait'],['16:9','Landscape'],['9:16','Story']];
const sessionKey='personalos-cloud-image-request';

export default function CreatorImageStudio({token,text,template}:{token:string;text:string;template?:any}){
 const [promptPreview,setPromptPreview]=useState('');
 const [brandMode,setBrandMode]=useState('snapshot'),[drafts,setDrafts]=useState<any[]>([]),[target,setTarget]=useState(''),[pendingJobs,setPendingJobs]=useState<any[]>([]);
 const [ratio,setRatio]=useState('1:1'),[direction,setDirection]=useState(''),[items,setItems]=useState<Generated[]>([]),[task,setTask]=useState(''),[status,setStatus]=useState(''),[progress,setProgress]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false),[budget,setBudget]=useState<{limitCredits:number;remainingCredits:number;reservationCredits:number;uncertain:boolean}|null>(null),[retry,setRetry]=useState(0);const seq=useRef(0);
 async function history(){if(!token){setItems([]);return;}const n=++seq.current;try{const r=await fetch('/api/image',{headers:{Authorization:'Bearer '+token},cache:'no-store'});const d=await r.json();if(n!==seq.current)return;if(!r.ok)throw new Error(d.error);setItems(d.items||[]);if(d.budget)setBudget(d.budget);setPendingJobs(d.pending||[]);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'未能讀取生成圖片');}}
 useEffect(()=>{if(token)void history();},[template?.id]);
 useEffect(()=>{if(token)fetch('/api/content?scope=cloud',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json()).then(d=>setDrafts(d.items||[])).catch(()=>{});},[token]);
 useEffect(()=>{setError('');setBudget(null);setLoading(false);setStatus('');setProgress(0);void history();const saved=token?sessionStorage.getItem(sessionKey)||'':'';setTask(saved);return()=>{seq.current++;};},[token]);
 useEffect(()=>{if(!task||!token)return;let live=true,timer:number;async function poll(){setLoading(true);setStatus('checking');try{const r=await fetch('/api/image',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action:'resume',taskId:task}),cache:'no-store'});const d=await r.json();if(!live)return;if(d.status==='failed'){sessionStorage.removeItem(sessionKey);setTask('');setStatus('failed');setProgress(0);setLoading(false);setError(d.error||'圖片生成失敗；沒有自動重試');void history();return;}if(!r.ok)throw new Error(d.error||'圖片狀態暫時未能讀取');setStatus(d.status||'in_progress');setProgress(Number(d.progress)||0);if(d.status==='completed'){if(d.attachmentError)setError(d.attachmentError);sessionStorage.removeItem(sessionKey);setTask('');setLoading(false);await history();return;}timer=window.setTimeout(poll,3000);}catch(e){if(live){setError(e instanceof Error?e.message:'圖片狀態未能讀取');setStatus('paused');setProgress(0);setLoading(false);}}}void poll();return()=>{live=false;window.clearTimeout(timer);};},[task,token,retry]);
 const chosen=target?drafts.find(r=>r.id===target.split('|')[0])?.revisions.at(-1).outputs.find((o:any)=>o.platform===target.split('|')[1]):null;const content=chosen?.body||text;
 async function generate(){if(!token||content.trim().length<10||task)return;setError('');setLoading(true);setStatus('submitting');setProgress(0);const requestId=crypto.randomUUID();sessionStorage.setItem(sessionKey,requestId);try{const r=await fetch('/api/image',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({requestId,text:content,visualDirection:direction,ratio,templateId:template?.id,brandMode,queueTarget:target?{id:target.split('|')[0],platform:target.split('|')[1],expectedVersion:drafts.find(r=>r.id===target.split('|')[0])?.version}:null})});const d=await r.json();if(!r.ok){if(d.requestState==='not-created')sessionStorage.removeItem(sessionKey);else setTask(d.taskId||requestId);throw new Error(d.error);}if(d.budget)setBudget(d.budget);sessionStorage.setItem(sessionKey,d.taskId);setTask(d.taskId);setStatus(d.status||'queued');}catch(e){setError(e instanceof Error?e.message:'圖片提交未完成');if(sessionStorage.getItem(sessionKey))setTask(requestId);setStatus('paused');setLoading(false);}}
 return <section className="creator-image-panel" aria-labelledby="creator-image-title"><header><span><ImageIcon size={20}/></span><div><h2 id="creator-image-title">為內容生成品牌配圖</h2><p>結合今次內容同你嘅品牌風格，生成一張配圖。</p></div><button className="quiet" disabled={!token||!!task} onClick={()=>void history()} aria-label="重新讀取生成圖片"><RefreshCw size={15}/></button></header>
  <p>模板：{template?.name||'未選模板（直接用品牌設定）'}</p>{template&&<label>品牌版本<select value={brandMode} onChange={e=>setBrandMode(e.target.value)}><option value="snapshot">沿用模板品牌</option><option value="latest">套用最新Ommi Brain</option></select></label>}<label>配圖目標<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">獨立圖片</option>{drafts.flatMap(r=>r.revisions.at(-1).outputs.map((o:any)=><option key={r.id+o.platform} value={r.id+'|'+o.platform}>{o.platform} · {o.title||o.body.slice(0,30)}</option>))}</select></label><div className="creator-image-controls"><label>Visual direction <textarea value={direction} maxLength={800} onChange={e=>setDirection(e.target.value)} placeholder="例如：大膽、極簡、強烈紫色重點；留空由內容自動決定。"/></label><fieldset><legend>Aspect ratio</legend><div>{ratios.map(([id,label])=><button type="button" key={id} aria-pressed={ratio===id} className={ratio===id?'selected':''} onClick={()=>setRatio(id)}><strong>{id}</strong><span>{label}</span></button>)}</div></fieldset></div>
  <button className="quiet" disabled={!token||content.trim().length<10||loading} onClick={async()=>{setError('');try{const r=await fetch('/api/image',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action:'preview',text:content,visualDirection:direction,ratio,templateId:template?.id,brandMode})});const d=await r.json();if(!r.ok)throw Error(d.error);setPromptPreview(d.prompt);if(d.budget)setBudget(d.budget);}catch(e){setError(e instanceof Error?e.message:'預覽失敗');}}}>預覽最終Prompt（不收費）</button>{promptPreview&&<details open><summary>本次生成Prompt</summary><p style={{whiteSpace:'pre-wrap'}}>{promptPreview}</p></details>}<div className="creator-image-contract"><span>gpt-image-2.5-flare</span><span>1K</span><span>1 image</span><span>≈ 3 credits*</span></div>
  <div className="creator-image-action"><p>*固定1K；公開參考價約3credits／張，最終以帳戶報價為準。{budget?`ToAPI有效上限${budget.limitCredits} credits，已核對剩餘${budget.remainingCredits} credits；新請求需預留${budget.reservationCredits} credits（不是實際費用）${budget.uncertain?'，上次扣費仍待核對':''}`:'ToAPI額度待讀取'}，備用模型亦只用1K，不自動付費重試。品牌參考圖尚未傳送，今版使用顏色、字體、語氣及watermark。</p>{!token?<Link className="quiet" href="/connections">先連接Supabase</Link>:<button className="button" disabled={loading||!!task||content.trim().length<10} onClick={()=>void generate()}>{task&&status==='paused'?'等待恢復':loading||task?<><LoaderCircle className="spin" size={16}/> Generating {progress?`${progress}%`:''}</>:<><Sparkles size={16}/> Generate image</>}</button>}</div>
  {task&&status==='paused'&&<button className="quiet" onClick={()=>{sessionStorage.removeItem(sessionKey);setTask('');setStatus('');setError('');}}>保留舊請求待核對，開始另一張</button>}{!task&&pendingJobs.map(p=><button className="quiet" key={p.taskId} onClick={()=>{sessionStorage.setItem(sessionKey,p.taskId);setTask(p.taskId);}}>恢復舊圖片 {p.taskId.slice(0,8)}</button>)}{task&&status==='paused'&&<button type="button" className="quiet" disabled={!token} onClick={()=>{setError('');setRetry(n=>n+1);}}>恢復查詢／保存同一張圖（不重新生成）</button>}
  {status&&task&&<p className="creator-image-status" role="status">Task {task} · {status==='paused'?'查詢／保存暫停；保留原task，請恢復查詢':`${status} · ${progress}%`}</p>}{error&&<p className="notice" role="alert">{error}</p>}
  {items.length>0&&<div className="creator-image-results">{items.map(item=><article key={item.taskId}><Image unoptimized src={item.signedUrl} alt="Creator Studio生成圖片" width={1024} height={item.size==='9:16'?1820:item.size==='4:5'?1280:item.size==='16:9'?576:1024} sizes="(max-width: 700px) 90vw, 380px"/><div><strong>{item.size} · {item.resolution}</strong><span>{item.model}</span><small>Supabase saved · {item.observedCredits==null?'實際費用待核對':item.observedCredits+' credits'}</small></div><button className="quiet" disabled={!target||loading} onClick={async()=>{setError('');setLoading(true);try{const [id,platform]=target.split('|');const r=await fetch('/api/content',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action:'attachImage',id,platform,expectedVersion:drafts.find(v=>v.id===id).version,imageTaskId:item.taskId})});const d=await r.json();if(!r.ok)throw Error(d.error);setDrafts(v=>v.map(x=>x.id===d.id?d:x));setError('已附到Queue，保存為Draft');}catch(e){setError(e instanceof Error?e.message:'附圖失敗');}finally{setLoading(false);}}}>附到所選Queue草稿</button><Link href="/queue">查看Queue</Link><details><summary>查看生成prompt</summary><p>{item.prompt}</p></details></article>)}</div>}
 </section>;
}
