'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';
import {Instagram,Music2,MessageCircle,AtSign,BookOpen,Newspaper,ArrowUpRight} from 'lucide-react';
import {presentInspirationCost,summarizeInspirationCosts} from '@/lib/inspiration-cost.mjs';
const platforms=[{id:'instagram',name:'Instagram',path:'instagram',icon:Instagram,color:'#fa3892'},{id:'tiktok',name:'TikTok',path:'tiktok',icon:Music2,color:'#00aaa7'},{id:'xiaohongshu',name:'小紅書 (XHS)',path:'xhs',icon:BookOpen,color:'#ff475d'},{id:'twitter',name:'X (Twitter)',path:'twitter',icon:AtSign,color:'#222'},{id:'threads',name:'Threads',path:'threads',icon:AtSign,color:'#444'},{id:'reddit',name:'Reddit',path:'reddit',icon:MessageCircle,color:'#ff5700'}];
export default function InspirationHub({token}:{token:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{const c=new AbortController();setData(null);setLoading(true);setError('');fetch('/api/inspiration?hub=1',{headers:{Authorization:'Bearer '+token},signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[token]);
 const costSummary=summarizeInspirationCosts(data?.runs||[]);const cost=presentInspirationCost(costSummary);
 return <div className="inspiration-hub"><header className="hub-heading"><div><h1>你的靈感總覽</h1><p>你關注咩、來源有幾新，同下一篇內容嘅方向。</p></div><button disabled>受眾與語言 · WIP</button></header>{error&&<p role="alert" className="notice">{error} <Link href="/connections">Connections</Link></p>}<section className="hub-stats" aria-label="靈感總覽統計">{[['追蹤分類','—','分類設定尚未接通'],['我的來源',data?data.sources.length:'—','帳號與社群，非正式名單'],['已保留或使用','—','使用事件尚未接通'],['預估 TikHub 抓取費用',cost.value,cost.note]].map(([title,value,note])=><div key={String(title)}><span>{title}</span><strong>{loading?'…':value}</strong><small>{note}</small></div>)}</section>{data&&<section className="hub-cost" aria-label="抓取費用核對"><div><strong>費用核對</strong><span>{costSummary.status==='partial'?'部分估算':costSummary.status==='estimated'?'已估算':costSummary.status==='verified_zero'?'已核實免收費':'費用待核對'}</span></div><p>近30日 TikHub runs：{costSummary.pricedRuns}/{costSummary.totalRuns} 有可靠估價。此頁只讀 Supabase 已保存紀錄，不會呼叫 TikHub。</p></section>}<section className="hub-directory"><header><h2>你的靈感來源</h2><span>從 Supabase 讀回 · 已保存</span></header><div className="hub-table-scroll"><table><thead><tr><th>社交平台</th><th>帖文</th><th>內容更新</th><th>本批抓取估價</th><th>已用素材</th></tr></thead><tbody>{platforms.map(p=>{const posts=data?.posts.filter((r:any)=>r.platform===p.id)||[];const sources=data?.sources.filter((r:any)=>r.platform===p.id)||[];const times=posts.map((p:any)=>p.fetched_at).filter(Boolean).sort();const platformCost=presentInspirationCost(summarizeInspirationCosts((data?.runs||[]).filter((r:any)=>r.platform===p.id)));const Icon=p.icon;return <tr key={p.id}><td><Link className="hub-platform" href={'/inspiration/'+p.path}><span style={{color:p.color,background:p.color+'10'}}><Icon size={21}/></span><div><strong>{p.name}</strong><small>{data?`${sources.length} 個來源`:'來源待讀取'} · <span>查看帖子 ↗</span></small></div></Link></td><td>{data?posts.length:'—'}</td><td>{times.length?<time>{new Date(times.at(-1)).toLocaleString('zh-HK',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time>:'—'}</td><td>{data?<>{platformCost.value}<small>{platformCost.note}</small></>:'—'}</td><td>—<small>未接通</small></td></tr>;})}</tbody><thead><tr><th>新聞與其他訊號</th><th>帖文</th><th>來源</th><th>更新方式</th><th>已用素材</th></tr></thead><tbody><tr><td><Link className="hub-platform" href="/feed"><Newspaper size={21}/><div><strong>RSS News</strong><small>原版HeyOmmi RSS預設</small></div></Link></td><td>{data?data.newsCount:'—'}</td><td>RSS</td><td>手動首批</td><td>—</td></tr>{['AI Feed','Crypto Feed'].map(n=><tr className="hub-disabled" key={n}><td><strong>{n}</strong><small>獨立來源尚未接通</small></td><td>—</td><td>WIP</td><td>—</td><td>—</td></tr>)}</tbody></table></div><p className="hub-footnote">費用只計此 workspace 近30日 TikHub 已保存 runs；未知費用不當作零，估價不是帳單。</p></section><Link className="text-link" href="/inspiration/all">直接查看全部已抓取帖子 <ArrowUpRight size={14}/></Link></div>;
}
