'use client';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import rss from '../config/rss-sources.json';
import {Search,Settings2,RefreshCw,ExternalLink,BookOpen} from 'lucide-react';
type Item={post_id:string;caption:string;title:string;post_url:string;account:string;score:number|null;comments:number|null;[key:string]:unknown};
export default function NewsFeed({choose,token}:{choose:(item:Item)=>void;token:string}){
 const [data,setData]=useState<{items:Item[];fetchedAt?:string;fetchEnabled?:boolean;mode?:string;workspaceId?:string;sync?:{verified:boolean;matched:number}}>({items:[]}),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [generating,setGenerating]=useState(''),[draft,setDraft]=useState<any>(null),[generateError,setGenerateError]=useState('');const generatingRef=useRef(false);const currentToken=useRef(token);
 async function rewrite(item:Item){if(generatingRef.current)return;const startedToken=token;generatingRef.current=true;setGenerating(item.post_id);setDraft(null);setGenerateError('');try{const r=await fetch('/api/feed/rewrite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({postId:item.post_id,requestId:crypto.randomUUID()})});const d=await r.json();if(currentToken.current!==startedToken)return;if(!r.ok)throw new Error(d.error+(d.draftId?'（本地請求 '+d.draftId+'，請先核對，勿重複付費）':''));setDraft(d);}catch(e){if(currentToken.current===startedToken)setGenerateError(e instanceof Error?e.message:'生成未完成；請先核對請求，勿立即重試');}finally{setGenerating('');generatingRef.current=false;}}
 const [reading,setReading]=useState(''),[articleError,setArticleError]=useState(''),[expanded,setExpanded]=useState(''),[topic,setTopic]=useState('all');
 async function article(item:Item){const startedToken=token;setReading(item.post_id);setArticleError('');try{const r=await fetch('/api/feed',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action:'read-article',postId:item.post_id})});const d=await r.json();if(currentToken.current!==startedToken)return;if(!r.ok)throw new Error(d.error);setData(prev=>({...prev,items:prev.items.map(i=>i.post_id===item.post_id?{...i,article:d.article}:i)}));setExpanded(item.post_id);}catch(e){if(currentToken.current===startedToken)setArticleError(e instanceof Error?e.message:'正文未能讀取');}finally{setReading('');}}
 const [sourceId,setSourceId]=useState('huggingface-blog');
 const requestSequence=useRef(0);
 async function load(sync=false){const sequence=++requestSequence.current;setBusy(true);setError('');try{const r=await fetch('/api/feed',sync?{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action:'fetch-rss',sourceId})}:{cache:'no-store',headers:{Authorization:'Bearer '+token}});const d=await r.json();if(sequence!==requestSequence.current)return;if(!r.ok)throw new Error(d.error);setData(d);}catch(e){if(sequence!==requestSequence.current)return;setData({items:[]});setError(e instanceof Error?e.message:'讀取失敗');}finally{if(sequence===requestSequence.current)setBusy(false);}}
 useEffect(()=>{currentToken.current=token;setExpanded('');setArticleError('');setDraft(null);setGenerateError('');setData({items:[]});void load();return()=>{requestSequence.current++;};},[token]);
 const shown=data.items.filter(i=>(topic==='all'||i.template===topic)&&(i.caption+' '+i.account).toLowerCase().includes(query.toLowerCase()));
 return <section className="newsroom"><header className="newsroom-header"><div><span className="tag">OMMI NEWSROOM · RSS</span><h1>Newsroom</h1><p>由原始文章出發，寫成有你品牌觀點嘅內容。</p></div><button className="quiet" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></header>
 <div className="newsroom-guide"><BookOpen size={20}/><div><small>來源 → 正文 → OMMI BRAIN → 草稿</small><strong>揀一篇令你有嘢想講嘅文章。</strong></div><Link href="/voice">Ommi Brain ↗</Link></div>
 <div className="newsroom-toolbar"><div className="work-tabs"><span className="button">Latest</span><button disabled>Trending · WIP</button><button disabled>Explore · WIP</button></div><details><summary><Settings2 size={16}/> RSS來源設定</summary><div className="rss-settings"><label>沿用原版RSS來源清單<select value={sourceId} onChange={e=>setSourceId(e.target.value)}>{rss.sources.map(s=><option key={s.id} value={s.id}>{s.name} · {s.template}</option>)}</select></label><button className="button" disabled={busy||!token} onClick={()=>void load(true)}>抓取3篇並保存Supabase</button><small>每次手動抓取；沒有背景排程。</small></div></details></div>
 <label className="newsroom-search"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stories, sources, or topics…" aria-label="搜尋文章"/></label>
 <div className="newsroom-topics"><strong>Topics</strong>{[['all','All'],['ai','AI'],['news','World'],['crypto','Crypto']].map(([id,label])=><button key={id} className={topic===id?'selected':''} aria-pressed={topic===id} onClick={()=>setTopic(id)}>{label}</button>)}</div>
 <div className="newsroom-count"><span>{shown.length} stories · {data.mode==='supabase-live'?'Supabase 已讀回':'等待連線'}</span><span>RSS原文 · 非AI編輯精選</span></div>
 {error&&<p role="alert">{error}</p>}{articleError&&<p className="notice" role="alert">{articleError}。未取得正文前不會啟動品牌改寫；可查看原文連結。</p>}{generateError&&<p role="alert">{generateError}</p>}{generating&&<p role="status">讀取原文並按Ommi Brain改寫，保存Supabase中…</p>}
 {draft&&<section className="panel"><h2>品牌草稿已準備好</h2><p className="success">Supabase已保存並讀回 · {draft.model}</p>{draft.revisions.at(-1).outputs.map((o:any)=><article key={o.platform}><h3>{o.platform} · {o.title}</h3><p className="brand-copy">{o.body}</p></article>)}<Link href="/queue">查看Queue →</Link></section>}
 {busy?<p role="status">讀取中…</p>:!shown.length?<div className="panel">未有符合條件嘅文章。可從RSS來源設定抓取。</div>:<div className="newsroom-grid">{shown.map(i=>{const a=i.article as any;return <article className="story-card" key={i.post_id}><header><span className="story-avatar">{i.account.slice(0,1)}</span><div><strong>{i.account}</strong><small>RSS · {String(i.template||'News')}</small></div><a href={i.post_url} target="_blank" rel="noopener noreferrer" aria-label="開啟原始文章"><ExternalLink size={16}/></a></header>{(a?.image_url||i.image_url)&&<img className="news-cover" src={String(a?.image_url||i.image_url)} alt="" loading="lazy" referrerPolicy="no-referrer"/>}<h2>{i.title}</h2><p className="story-summary">{a?.text?.slice(0,400)||(i.caption!==i.title?i.caption.slice(i.title.length).trim():'RSS只提供標題。讀取原文後可顯示正文摘要。')}</p><div className="story-evidence"><strong>{a?'已提取公開正文':'正文待讀取'}</strong><span>{a?`${a.character_count.toLocaleString()}字元 · 已保存Supabase${a.truncated?' · 儲存內容已截短':''}`:'保留原始來源；不憑標題補寫文章內容。'}</span></div><footer><button className="quiet" disabled={!!reading||!!generating} onClick={()=>a?setExpanded(expanded===i.post_id?'':i.post_id):void article(i)}>{reading===i.post_id?'讀取中…':expanded===i.post_id?'收起正文':a?'閱讀正文':'讀取原文'}</button><button className="button" disabled={!!generating||!!reading||!token} onClick={()=>choose(i)}>Create from this →</button></footer>{expanded===i.post_id&&a&&<div className="story-body"><small>公開頁面提取，未保證包含原站所有內容。</small><p>{a.text}</p><a href={i.post_url} target="_blank" rel="noopener noreferrer">到原站核對 ↗</a></div>}</article>;})}</div>}
 </section>;
}
