'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Output={platform:string;title:string;body:string};
type RecordItem={id:string;version:number;status:string;provenance?:string;brand:{owner:string;revision:string};brief:{input:string;platforms:string[];source:unknown};request:unknown;model?:string;usage?:unknown;cost?:unknown;revisions:{version:number;status:string;outputs:Output[];review:unknown}[]};
async function call(body:unknown){const r=await fetch('/api/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d as RecordItem;}
export default function TeacherWorkbench({brief}:{brief?:()=>unknown}){
 const [enabled,setEnabled]=useState(false),[items,setItems]=useState<RecordItem[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 async function load(){setError('');try{const r=await fetch('/api/content',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setEnabled(d.enabled);setItems(d.items||[]);}catch(e){setError(e instanceof Error?e.message:'讀取失敗');}finally{setLoaded(true);}}
 useEffect(()=>{void load();},[]);
 function update(record:RecordItem){setItems(old=>[record,...old.filter(r=>r.id!==record.id)]);setSelected(record.id);}
 if(!loaded)return <p role="status">檢查老師工作區…</p>;
 if(!enabled)return error?<p role="alert">{error}</p>:null;
 const active=items.find(r=>r.id===selected);
 return <section className="panel teacher-workbench"><span className="tag neutral">老師本地測試 · 不是學生已解鎖</span><h2>請求 → 草稿 → 版本 → 批准</h2><p>Terra真實改寫已接入老師測試。首輪總預算200 ToAPI credits；每個請求只試一次。fixture與手動匯入維持獨立標記。</p><div className="card-actions">{brief&&<button className="quiet" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{update(await call({action:'prepare',brief:brief()}));}catch(e){setError(e instanceof Error?e.message:'準備失敗');}finally{setBusy(false);}}}>保存生成請求（不呼叫API）</button>}<button className="quiet" onClick={()=>void load()}>重讀本地記錄</button><Link href="/queue">前往 Queue →</Link></div>{error&&<p role="alert">{error}</p>}<label>選本地請求<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">請選擇</option>{items.map(r=><option key={r.id} value={r.id}>{r.brand.owner} · {r.status} · v{r.version} · {r.id.slice(0,8)}</option>)}</select></label>{active&&<Editor key={active.id+':'+active.version} record={active} update={update}/>}</section>;
}
function Editor({record:r,update}:{record:RecordItem;update:(r:RecordItem)=>void}){
 const last=r.revisions.at(-1);const [json,setJson]=useState(''),[mode,setMode]=useState('manual'),[outputs,setOutputs]=useState<Output[]>(last?.outputs||[]),[reviewer,setReviewer]=useState(''),[checks,setChecks]=useState({facts:false,voice:false,format:false}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function mutate(action:string,extra:object){setBusy(true);setError('');try{update(await call({id:r.id,expectedVersion:r.version,action,...extra}));}catch(e){setError(e instanceof Error?e.message:'操作失敗');}finally{setBusy(false);}}
 const change=(i:number,key:'title'|'body',value:string)=>setOutputs(old=>old.map((o,j)=>i===j?{...o,[key]:value}:o));
 return <div><a className="quiet" href={`/api/content/export?id=${r.id}`} download>下載已保存簡報與版本</a><p><strong>{r.status} · v{r.version}</strong> · {r.provenance||'尚未有輸出'} · 品牌 {r.brand.revision}</p><p className="small-copy">本地 .student-data 保存；不是Supabase或已發布內容。模型／usage／credits見以下紀錄。</p><p className="small-copy">{r.model||'未呼叫模型'} · {JSON.stringify(r.usage||null)} · {JSON.stringify(r.cost||null)}</p><details><summary>來源、原文與生成請求</summary><pre className="request-json">{JSON.stringify({brief:r.brief,request:r.request},null,2)}</pre></details>{!last?<><h3>執行已保存請求</h3><button className="button" disabled={busy} onClick={()=>void mutate('generate',{})}>以 gpt-5.6-terra 生成 · 消耗credits</button><h3>或匯入模型回應JSON</h3><p>格式：outputs陣列，每項包含platform、title、body。只接受請求指定平台。</p><button className="quiet" onClick={()=>{setMode('fixture');setJson(JSON.stringify({outputs:r.brief.platforms.map(platform=>({platform,title:platform==='Newsletter'?'測試Newsletter':'',body:'這是本地流程測試文字，不是模型生成或正式品牌內容。'}))},null,2));}}>載入明確標示的測試fixture</button><label>回應來源<select value={mode} onChange={e=>setMode(e.target.value)}><option value="manual">手動匯入（模型來源未驗證）</option><option value="fixture">本地fixture測試</option></select></label><label>Response JSON<textarea value={json} onChange={e=>setJson(e.target.value)} rows={8}/></label><button className="button" disabled={busy} onClick={()=>{try{const parsed=JSON.parse(json);void mutate('import',{outputs:parsed.outputs,mode});}catch{setError('請貼入有效JSON');}}}>驗證並保存草稿</button></>:<><h3>修改目前版本</h3>{outputs.map((o,i)=><fieldset key={o.platform}><legend>{o.platform}</legend>{o.platform==='Newsletter'&&<label>標題<input value={o.title} onChange={e=>change(i,'title',e.target.value)}/></label>}<label>正文<textarea value={o.body} rows={6} onChange={e=>change(i,'body',e.target.value)}/></label></fieldset>)}<button className="button" disabled={busy||JSON.stringify(outputs)===JSON.stringify(last.outputs)} onClick={()=>void mutate('edit',{outputs})}>另存 Human Edit 版本</button><h3>批准已保存版本 v{r.version}</h3><p>未保存的編輯不能直接批准。修改已批准內容會建立新版本，重新等待覆核。</p><label>覆核者<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label>{(['facts','voice','format'] as const).map(k=><label key={k}><input type="checkbox" checked={checks[k]} onChange={e=>setChecks(v=>({...v,[k]:e.target.checked}))}/>{({facts:'事實與來源已核對',voice:'語氣已核對',format:'平台格式已核對'})[k]}</label>)}<button className="quiet" disabled={busy||r.status==='approved'||JSON.stringify(outputs)!==JSON.stringify(last.outputs)||!reviewer.trim()||!Object.values(checks).every(Boolean)} onClick={()=>void mutate('approve',{reviewer,checks})}>批准此已保存版本</button><button disabled>Publish · 未開放</button><h3>版本記錄</h3>{r.revisions.map(v=><details key={v.version}><summary>v{v.version} · {v.status}</summary>{v.outputs.map(o=><div key={o.platform}><strong>{o.platform} · {o.title}</strong><p style={{whiteSpace:'pre-wrap'}}>{o.body}</p></div>)}</details>)}</>}{error&&<p role="alert">{error}</p>}</div>;
}
