import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';
import https from 'node:https';
import {createHash} from 'node:crypto';
import {ContentError} from './content-engine.mjs';
import {extractArticle} from './article-reader.mjs';

export function sourceUrl(value){let u;try{u=new URL(value);}catch{throw new ContentError('請貼完整HTTPS連結');}if(u.protocol!=='https:'||u.username||u.password||u.port||isIP(u.hostname.replace(/^\[|\]$/g,''))||/^(localhost)$|\.(local|internal|localhost)$/i.test(u.hostname)||!u.hostname.includes('.'))throw new ContentError('只接受公開HTTPS網站連結');u.hash='';const host=u.hostname.replace(/^(www|mobile)\./,'');if(['x.com','twitter.com'].includes(host)){const match=u.pathname.match(/^\/(?:[A-Za-z0-9_]+|i\/web)\/status\/(\d{10,25})\/?$/);if(!match)throw new ContentError('請貼X單一帖子的status連結');return {url:'https://x.com/i/web/status/'+match[1],tweetId:match[1],provider:'tikhub'};}return {url:u.href,provider:'direct-html'};}
export function sourceRequestId(url){const h=createHash('sha256').update(url).digest('hex');return [h.slice(0,8),h.slice(8,12),h.slice(12,16),h.slice(16,20),h.slice(20,32)].join('-');}
export function parseTweet(raw,id){const data=raw?.data;if(raw?.code!==200||!data)throw new ContentError('TikHub未回傳成功帖子');let found=null,visited=0;function walk(v){if(!v||typeof v!=='object'||visited++>10000)return;const identity=v.id_str||v.rest_id||v.tweet_id||v.id;if(typeof identity==='string'&&identity===id&&(v.text||v.full_text||v.legacy?.full_text))found=v;for(const x of Object.values(v))if(x&&typeof x==='object')walk(x);}walk(data);if(!found)throw new ContentError('未確認回應內的原帖ID，不使用引用帖子代替');const text=found.note_tweet?.note_tweet_results?.result?.text||found.full_text||found.legacy?.full_text||found.text;if(typeof text!=='string'||!text.trim())throw new ContentError('帖子未提供可讀正文');return {title:'X · '+(found.author?.screen_name||found.author?.name||id),text,url:'https://x.com/i/web/status/'+id,author:found.author?.screen_name||null,content_depth:'provider-post-text',media:found.media||[],fetchedAt:new Date().toISOString()};}
export function publicIPv4(value){const a=value.split('.').map(Number);return a.length===4&&a.every(n=>Number.isInteger(n)&&n>=0&&n<=255)&&![0,10,127].includes(a[0])&&a[0]<224&&!(a[0]===169&&a[1]===254)&&!(a[0]===172&&a[1]>=16&&a[1]<=31)&&!(a[0]===192&&(a[1]===168||a[1]===0))&&!(a[0]===100&&a[1]>=64&&a[1]<=127)&&!(a[0]===198&&a[1]>=18&&a[1]<=19);}
async function htmlPage(url){const addresses=await lookup(new URL(url).hostname,{all:true,family:4});if(!addresses.length||addresses.some(a=>!publicIPv4(a.address)))throw new ContentError('不讀取私人網絡位址');const address=addresses[0].address;
 return new Promise((resolve,reject)=>{const req=https.get(url,{lookup:(_hostname,options,cb)=>options.all?cb(null,[{address,family:4}]):cb(null,address,4),headers:{Accept:'text/html','User-Agent':'PersonalOS/1.0'}},async res=>{try{if([301,302,303,307,308].includes(res.statusCode)){res.resume();return resolve({redirect:res.headers.location});}if(res.statusCode!==200||!res.headers['content-type']?.includes('text/html'))throw new ContentError('網站未提供公開HTML正文');const chunks=[];let bytes=0;for await(const chunk of res){bytes+=chunk.length;if(bytes>3000000){res.destroy();throw new ContentError('文章頁面超過3MB');}chunks.push(chunk);}resolve({html:Buffer.concat(chunks).toString('utf8')});}catch(e){reject(e);}});req.setTimeout(15000,()=>req.destroy(new Error('網站讀取逾時')));req.on('error',reject);});}
export async function fetchLink(input,{fetcher=fetch,key=process.env.TIKHUB_API_KEY}={}){const parsed=sourceUrl(input);
 if(parsed.tweetId){try{const response=await fetcher('https://api.fxtwitter.com/status/'+parsed.tweetId,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(3500),redirect:'error'});if(response.ok){const fx=await response.json();const source=parseTweet({code:200,data:fx.tweet},parsed.tweetId);return {source:{...source,provider:'fxtwitter'},raw:fx};}}catch{}if(!key)throw new ContentError('X連結需要已配置的TikHub key');const response=await fetcher('https://api.tikhub.io/api/v1/twitter/web/fetch_tweet_detail?tweet_id='+parsed.tweetId,{headers:{Authorization:'Bearer '+key},signal:AbortSignal.timeout(30000),redirect:'error'});if(!response.ok)throw new ContentError('TikHub讀取未完成（HTTP '+response.status+'）',502);const raw=await response.json();return {source:parseTweet(raw,parsed.tweetId),raw};}
 let url=parsed.url;for(let i=0;i<4;i++){const result=await htmlPage(url);if(result.redirect){url=sourceUrl(new URL(result.redirect,url).href).url;continue;}return {source:{...extractArticle(result.html,url),content_depth:'extracted-public-article'},raw:null};}throw new ContentError('網站轉址次數過多');
}
