import {createClient} from '@supabase/supabase-js';import {connectionConfig} from './read-only.mjs';import {ContentError} from './content-engine.mjs';import {costMetadata} from './inspiration-cost.mjs';
const fields={sources:['source_id','platform','account','profile_url','collection_reason','fetched_at'],runs:['run_id','provider','platform','requested_count','collected_count','request_count','estimated_cost_usd','fetched_at','status','raw_url','error'],posts:['post_id','source_id','platform','account','content_type','caption','published_at','post_url','like_count','comment_count','view_count','share_count','save_count','fetched_at','run_id','raw_url','notes'],media:['media_id','post_id','asset_index','media_type','source_media_url','drive_file_id','drive_url','archive_status','notes','visual_analysis','reverse_engineering_prompt','prompt_notes']};
const numeric=new Set(['requested_count','collected_count','request_count','estimated_cost_usd','asset_index','like_count','comment_count','view_count','share_count','save_count']);
const pk={sources:'source_id',runs:'run_id',posts:'post_id',media:'media_id'};
const platforms={rednote:'xiaohongshu',x:'twitter',X:'twitter'};
export function mapStudentImport(input,workspace){const out={};let total=0;for(const [table,columns] of Object.entries(fields)){const title=table[0].toUpperCase()+table.slice(1),rows=input[title];if(!Array.isArray(rows))throw new ContentError('缺少'+title+'資料');if(rows.length>500)throw new ContentError('每表最多500筆，請先分批');total+=rows.length;const seen=new Set();out[table]=rows.map(raw=>{const id=raw[pk[table]];if(typeof id!=='string'||!id.trim()||seen.has(id))throw new ContentError('ID須為不重複字串：'+table);seen.add(id);const row={workspace_id:workspace};for(const c of columns){let v=raw[c];if(v===undefined||v==='')v=null;if(v!==null&&numeric.has(c)){if(!Number.isFinite(Number(v)))throw new ContentError('無效數字 '+c);if(c==='estimated_cost_usd')v=Number(v);else {if(!/^-?\d+$/.test(String(v)))throw new ContentError('需要整數 '+c);v=String(v);}}if(v!==null&&['published_at','fetched_at'].includes(c)){if(!Number.isFinite(Date.parse(v)))throw new ContentError('無效日期 '+c);v=new Date(v).toISOString();}row[c]=v;}if(row.platform)row.platform=platforms[row.platform]||row.platform;row.metadata={student_import:true,original_fields:raw};if(table==='sources')row.metadata.inspiration_origin='student-import';if(table==='runs')row.metadata={...row.metadata,inspiration_origin:'student-import',...costMetadata(row.estimated_cost_usd,'imported')};if(table==='posts')row.metadata={...row.metadata,inspiration_origin:'student-import',inspiration:{post_id:id,source_id:row.source_id,platform:row.platform,account:row.account,caption:row.caption,post_url:row.post_url,published_at:row.published_at,content_depth:'imported-post-text',metrics:Object.fromEntries(['like_count','comment_count','view_count','share_count','save_count'].map(k=>[k,row[k]===null?null:Number(row[k])]))}};return row;});}if(!total)throw new ContentError('沒有資料');const sources=new Set(out.sources.map(r=>r.source_id)),posts=new Set(out.posts.map(r=>r.post_id)),runs=new Set(out.runs.map(r=>r.run_id));for(const p of out.posts){if(!sources.has(p.source_id)||p.run_id&&!runs.has(p.run_id))throw new ContentError('Posts關聯缺少Sources／Runs，請提供完整關聯批次');}for(const m of out.media)if(!posts.has(m.post_id))throw new ContentError('Media缺少對應Post');return out;}
export async function importStudentData(input,token,workspace,preview=true){const mapped=mapStudentImport(input,workspace);const summary=Object.fromEntries(Object.entries(mapped).map(([t,r])=>[t,r.length]));if(preview)return {preview:true,summary};const conf=connectionConfig();const db=createClient(conf.url,conf.key,{global:{headers:{Authorization:'Bearer '+token}},auth:{persistSession:false,autoRefreshToken:false}});
 // Validate conflicts in every table before writing anything. Do not erase manual edits.
 for(const [t,rows]of Object.entries(mapped)){if(!rows.length)continue;const {data,error}=await db.from(t).select('*').eq('workspace_id',workspace).in(pk[t],rows.map(r=>r[pk[t]]));if(error)throw new ContentError('無法檢查'+t);for(const old of data){const row=rows.find(r=>r[pk[t]]===old[pk[t]]);for(const k of fields[t])if(['published_at','fetched_at'].includes(k)&&old[k]&&row[k]?Date.parse(old[k])!==Date.parse(row[k]):String(old[k]??'')!==String(row[k]??''))throw new ContentError('已有不同內容：'+t+' '+old[pk[t]]+'；未覆寫',409);}}
 for(const [t,rows]of Object.entries(mapped)){if(!rows.length)continue;const {error}=await db.from(t).upsert(rows,{onConflict:'workspace_id,'+pk[t],ignoreDuplicates:true});if(error)throw new ContentError('匯入'+t+'未完成；保留原資料，可核對後重跑');const {data,error:err}=await db.from(t).select(pk[t]).eq('workspace_id',workspace).in(pk[t],rows.map(r=>r[pk[t]]));if(err||data.length!==rows.length)throw new ContentError('讀回數量不符：'+t);}return {verified:true,summary};}
