import {NextResponse} from 'next/server';
import {randomUUID,createHash} from 'node:crypto';
import {cloudRuntime} from '@/lib/cloud-runtime.mjs';
import {runtimeBrain} from '@/lib/ommi-brain.mjs';
import {assertLocalRequest,ContentError} from '@/lib/content-engine.mjs';
import {token} from '@/lib/api';
import {imageStorage,imagePreview} from '@/lib/image-storage';
import {validateAnalysis,visionRequest} from '@/lib/image-template.mjs';
export const dynamic='force-dynamic';export const maxDuration=120;
const headers={'Cache-Control':'no-store'};
async function templates(rt:any){const rows=await rt.request('sources?'+new URLSearchParams({select:'metadata',workspace_id:'eq.'+rt.workspace,'metadata->>template_origin':'eq.personalos-image',order:'updated_at.desc',limit:'100'}));return rows.map((r:any)=>r.metadata);}
export async function GET(req:Request){try{const auth=token(req)!;const rt=await cloudRuntime(auth);const items=await templates(rt);return NextResponse.json({items:await Promise.all(items.filter((v:any)=>!v.archived).map(async(v:any)=>({...v,signedUrl:await imagePreview(auth,v.reference.path,rt.workspace).catch(()=>null)}))),budget:await rt.budget(),pending:await rt.pendingJobs('analysis'),analyses:(await rt.request('runs?'+new URLSearchParams({select:'metadata',workspace_id:'eq.'+rt.workspace,'metadata->>kind':'eq.analysis','metadata->>state':'eq.completed',order:'created_at.desc',limit:'10'}))).map((r:any)=>({taskId:r.metadata.id,status:'completed'}))},{headers});}catch(e){return error(e);}}
function error(e:any,job?:any){return NextResponse.json({error:e instanceof ContentError?e.message:'操作未完成，請恢復原請求',requestId:job?.id,state:job?.state||'not-created'},{status:e instanceof ContentError?e.status:503,headers});}
export async function POST(req:Request){let job:any,rt:any;try{assertLocalRequest(req,{allowMultipart:true});const auth=token(req)!;rt=await cloudRuntime(auth);
 if(req.headers.get('content-type')?.includes('multipart/form-data')){if(Number(req.headers.get('content-length'))>3500000)throw new ContentError('圖片請縮小至3MB');const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||file.size>3000000||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new ContentError('只接受3MB內JPEG、PNG、WebP');const bytes=new Uint8Array(await file.arrayBuffer());const valid=(file.type==='image/jpeg'&&bytes[0]===255&&bytes[1]===216)||(file.type==='image/png'&&bytes[0]===137&&bytes[1]===80)||(file.type==='image/webp'&&Buffer.from(bytes.slice(0,4)).toString()==='RIFF'&&Buffer.from(bytes.slice(8,12)).toString()==='WEBP');if(!valid)throw new ContentError('圖片內容與格式不符');const id=randomUUID(),path=rt.workspace+'/references/'+id;const saved=await imageStorage(auth).upload(path,bytes,{contentType:file.type,upsert:false});if(saved.error)throw new ContentError('參考圖保存失敗',502);return NextResponse.json({reference:{path,contentType:file.type,sha256:createHash('sha256').update(bytes).digest('hex'),sourceUrl:String(form.get('sourceUrl')||'').slice(0,2000)},signedUrl:await imagePreview(auth,path,rt.workspace)},{headers});}
 const b=await req.json();
 if(b.action==='save'){const analysisJob=await rt.job(b.analysisId);if(analysisJob.kind!=='analysis'||analysisJob.state!=='completed')throw new ContentError('分析未完成');const name=String(b.name||'').trim();if(!name||name.length>100)throw new ContentError('請填100字內模板名稱');const analysis=validateAnalysis(b.analysis||analysisJob.analysis);const value={name,analysis,reference:analysisJob.payload.reference,brand:analysisJob.payload.brand,focus:b.focus||'style',analysisId:analysisJob.id,archived:!!b.archived};const saved=await rt.rpc('personalos_template',{p_workspace:rt.workspace,p_id:b.id||randomUUID(),p_expected:b.expectedVersion||0,p_template:value});return NextResponse.json(saved,{headers});}
 if(b.action==='recover'){job=await rt.job(b.requestId);if(job.kind!=='analysis')throw new ContentError('請求類型不符');}
 else if(b.action==='analyze'){if(!process.env.TOAPI_API_KEY)throw new ContentError('未配置ToAPI');const reference=b.reference;if(!reference?.path?.startsWith(rt.workspace+'/references/'))throw new ContentError('參考圖不屬於目前workspace',403);const snapshot=await rt.requireBrand();const brain=runtimeBrain(snapshot,await rt.client.ommiBrain(rt.workspace));const {data,error:downloadError}=await imageStorage(auth).download(reference.path);if(downloadError||!data||data.size>3000000)throw new ContentError('未能讀取參考圖');const bytes=Buffer.from(await data.arrayBuffer());const canonical={...reference,contentType:data.type,sha256:createHash('sha256').update(bytes).digest('hex')};const request=visionRequest({dataUrl:'data:'+data.type+';base64,'+bytes.toString('base64'),mode:b.mode||'auto',brand:brain});const claimed=await rt.claim(b.requestId,'analysis',{reference:canonical,brand:brain,mode:b.mode||'auto',model:request.model});job=claimed.job;if(claimed.claimed){try{const response=await fetch('https://toapis.com/v1/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+process.env.TOAPI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify(request),signal:AbortSignal.timeout(90000)});const raw=await response.json();job=await rt.update(job,'generated',{response:raw,providerHttpStatus:response.status});}catch{job=await rt.update(job,'unknown',{error:'分析提交或保存狀態未明，不自動重試'});throw new ContentError('請恢復原分析，勿重新付費',502);}}}
 else throw new ContentError('不支援的操作');
 if(job.state==='failed')throw new ContentError(job.error||'原分析失敗，未重新提交',502);if(job.state==='completed')return NextResponse.json(job,{headers});if(!job.response)throw new ContentError('分析仍在處理或狀態待核對，未重新付費',409);if(job.providerHttpStatus>=400){job=await rt.update(job,'failed',{error:'分析供應商回報HTTP '+job.providerHttpStatus});throw new ContentError(job.error,502);}if(job.response.choices?.[0]?.finish_reason!=='stop')throw new ContentError('分析未完整完成，原回應已保存',422);let parsed;try{parsed=JSON.parse(job.response.choices[0].message.content.replace(/^```(?:json)?\s*|\s*```$/g,''));}catch{throw new ContentError('分析JSON未能解析；原回應已保存',422);}const analysis=validateAnalysis(parsed);job=await rt.update(job,'completed',{analysis,usage:job.response.usage});return NextResponse.json(job,{headers});
 }catch(e){return error(e,job);}}
