import test from 'node:test';import assert from 'node:assert/strict';
import {createCloudContent} from '../lib/cloud-content.mjs';import {brandSummary} from '../lib/brand-summary.mjs';import {assertLocalRequest,validateOutputs} from '../lib/content-engine.mjs';
const snapshot=brandSummary({owner:'Fixture',documents:{company:{text:'A fictional company'},voice:{text:'Clear and direct'},look:{text:'#102030 #22AACC'}},outputPlatforms:['Threads','Instagram']},'Keep sources and facts');
function fixture(){const jobs=new Map();let failSave=true;return {workspace:'ws',jobs,requireBrand:async()=>snapshot,client:{ommiBrain:async()=>null,saveContentDraft:async record=>{if(failSave){failSave=false;throw Error('Storage unavailable');}return {...record,persistence:{verified:true}};}},claim:async(id,kind,payload)=>{if(jobs.has(id))return {claimed:false,job:jobs.get(id)};const job={id,kind,payload,version:0,state:'submitting'};jobs.set(id,job);return {claimed:true,job};},job:async id=>jobs.get(id),update:async(old,state,patch)=>{const saved=jobs.get(old.id);if(saved.version!==old.version)throw Error('version conflict');const next={...old,...patch,state,version:old.version+1};jobs.set(old.id,next);return next;}};}
test('cloud response survives failed save; recovery and repeated click do not call provider again',async()=>{const runtime=fixture();let calls=0;const fetcher=async(url,options)=>{calls++;assert.equal(url,'https://toapis.com/v1/chat/completions');assert.equal(JSON.parse(options.body).model,'deepseek-v4-flash');return Response.json({model:'deepseek-v4-flash',usage:{total_tokens:10},choices:[{finish_reason:'stop',message:{content:JSON.stringify({outputs:[{platform:'Video Script',body:'Hook: Start\nBody: A short explanation\nVisuals: Show the example\nCTA: Try it'}]})}}]});};const body={requestId:'11111111-1111-4111-8111-111111111111',text:'A fictional explanatory topic',platforms:['Video Script']};await assert.rejects(createCloudContent(runtime,body,{key:'fixture',fetcher}));const recovered=await createCloudContent(runtime,{requestId:body.requestId,action:'recover'},{key:'fixture',fetcher});assert.equal(recovered.revisions[0].outputs[0].platform,'Video Script');await createCloudContent(runtime,body,{key:'fixture',fetcher});assert.equal(calls,1);});
test('saved source and short personal angle reach the model separately',async()=>{const runtime=fixture();const sourceId='77777777-7777-4777-8777-777777777777';runtime.jobs.set(sourceId,{id:sourceId,kind:'source',state:'completed',source:{url:'https://example.com/article',text:'Verified fixture source text'}});let calls=0;const fetcher=async(_url,options)=>{calls++;const payload=JSON.stringify(JSON.parse(options.body));assert(payload.includes('Verified fixture source text'));assert(payload.includes('易明啲'));return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({outputs:[{platform:'Threads',body:'Fixture output'}]})}}]});};const requestId='88888888-8888-4888-8888-888888888888';await assert.rejects(createCloudContent(runtime,{requestId,text:'易明啲',sourceRequestIds:[sourceId],platforms:['Threads']},{key:'fixture',fetcher}),/Storage unavailable/);const result=await createCloudContent(runtime,{requestId,action:'recover'},{key:'fixture',fetcher});assert.equal(result.brief.source.content_depth,'retrieved-source-text');assert.equal(calls,1);});
test('oversized brand refuses without silent truncation',()=>{assert.throws(()=>brandSummary({...snapshot,documents:{...snapshot.documents,voice:{text:'x'.repeat(17000)}}},'skill'));});
test('provider authentication failure is terminal and recovery never resubmits',async()=>{const runtime=fixture();let calls=0;const fetcher=async()=>{calls++;return Response.json({error:{message:'invalid api key'}},{status:401});};const requestId='22222222-2222-4222-8222-222222222222';await assert.rejects(createCloudContent(runtime,{requestId,text:'Authentication rejection test',platforms:['Threads']},{key:'fixture',fetcher}),e=>e.terminal===true&&e.message.includes('401'));assert.equal(runtime.jobs.get(requestId).state,'failed');await assert.rejects(createCloudContent(runtime,{requestId,action:'recover'},{key:'fixture',fetcher}),e=>e.terminal===true);assert.equal(calls,1);});
test('script requires named sections',()=>{assert.throws(()=>validateOutputs([{platform:'Video Script',body:'Not a script'}],['Video Script']));});
test('only configured remote origins accept JSON mutations',()=>{const old=process.env.PERSONALOS_ALLOWED_ORIGINS;try{process.env.PERSONALOS_ALLOWED_ORIGINS='https://personalos.example';assert.doesNotThrow(()=>assertLocalRequest(new Request('https://personalos.example/api/create',{method:'POST',headers:{origin:'https://personalos.example','content-type':'application/json'}})));assert.throws(()=>assertLocalRequest(new Request('https://personalos.example/api/create',{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'}})));}finally{if(old===undefined)delete process.env.PERSONALOS_ALLOWED_ORIGINS;else process.env.PERSONALOS_ALLOWED_ORIGINS=old;}});
