const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const {parseHTML}=require('linkedom');
const base=__dirname+'/../';
const html=fs.readFileSync(base+'course/index.html','utf8');const {window,document}=parseHTML(html);
for(const el of document.querySelectorAll('input[type=checkbox]'))el.checked=el.hasAttribute('checked');
const store=new Map();let copied='',blob;
window.HTMLElement.prototype.focus=function(){};window.HTMLElement.prototype.scrollIntoView=function(){};window.HTMLElement.prototype.click=function(){};
const U=class extends URL{};U.createObjectURL=b=>{blob=b;return 'blob:test'};U.revokeObjectURL=()=>{};
const c=vm.createContext({document,window,URL:U,Blob,Date,console,setTimeout:()=>{},setInterval:()=>{},navigator:{clipboard:{writeText:async t=>{copied=t}}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}});
const run=s=>vm.runInContext(s,c);for(const script of document.querySelectorAll('script'))run(script.textContent);
(async()=>{
assert.equal(run('Object.keys(vaultTemplates).length'),15);
assert.equal(document.querySelector('[data-copy=p1]').disabled,false);
run("applyVault('/Users/student/YourCompany-Vault')");assert.equal(run("settingsReady('p1')"),false);assert(document.getElementById('requiredStatus').textContent.includes('Google Sheet'));run("activePaths=null;renderPaths()");
for(let i=1;i<=15;i++)assert.equal(document.getElementById('p'+i).textContent,run('vaultTemplates.p'+i));
assert.equal(document.querySelectorAll('.prompt-context').length,15);
assert.equal(document.querySelectorAll('.prompt-model').length,15);
run(`applyVault('/Users/student/My Folder/YourCompany-Vault');applySheet('https://docs.google.com/spreadsheets/d/1234567890abcdef/edit');applySupabase('abcdefghijklmnopqrst');document.getElementById('githubUsername').value='student-demo';applyAccount()`);
assert.equal(run("prerequisiteReady('p1')"),true);assert.equal(run("prerequisiteReady('p2')"),false);
document.getElementById('pluginsConfirmed').checked=true;
assert.equal(run("prerequisiteReady('p2')"),true);assert.equal(run("prerequisiteReady('p3')"),false);
document.getElementById('envConfirmed').checked=true;assert.equal(run('prerequisiteReady()'),true);
assert(run("promptText('p13')").includes('新對話：PersonalOS 部署'));
assert(run("promptText('p8')").includes('本Codex對話目前的工作資料夾')); assert(!run("promptText('p8')").includes('/Users/student/My Folder/PersonalOS'));
await run("copyPrompt('p8',document.querySelector('[data-copy=p8]'))");assert(copied.includes('同一')||copied.includes('既有'));assert.equal(document.getElementById('p8').closest('.prompt').querySelector('.prompt-copy-overlay').hidden,false);
run("applyVault('C:\\\\Users\\\\Student\\\\My Folder\\\\YourCompany-Vault')");
assert(run("promptText('p8')").includes('PersonalOS'));assert.equal(document.getElementById('p8').closest('.prompt').querySelector('.prompt-copy-overlay').hidden,true);
run('downloadPrompts()');const md=await blob.text();assert.equal((md.match(/## Prompt /g)||[]).length,15);assert(md.includes('PersonalOS 部署'));assert(!md.includes('【課堂修改邊界｜所有步驟適用】'));
assert.throws(()=>run("derivePaths('relative/folder')"));assert.throws(()=>run("normalizeSheet('https://example.org/sheet')"));
run("document.getElementById('vaultPath').dispatchEvent(new window.Event('input'))");assert.equal(document.getElementById('pluginsConfirmed').checked,false);assert.equal(run("prerequisiteReady('p3')"),false);
assert(html.includes('deepseek-v4-flash'));assert(!html.includes('額度固定20'));assert(!html.includes('開放04A'));assert(!html.includes('不能混作ToAPI credits'));assert(html.indexOf('id="preflight"')<html.indexOf('id="brand"'));assert(html.includes('已經IG來源實測')); assert(!html.includes('文字deepseek-v4-flash直連MINIMAX_API_KEY'));
console.log('PASS: 15 templates, 15 labels, staged gates, Mac/Windows substitution, successful copy overlay, stale copy invalidation, 15-prompt download, input reset and invalid-input rejection.');
})().catch(e=>{console.error(e);process.exit(1)});
