import test from 'node:test';import assert from 'node:assert/strict';
import {checkKeys,formatReport} from '../lib/key-check.mjs';
const GOOD={NEXT_PUBLIC_SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'sb_publishable_x',TOAPI_API_KEY:'sk-good',STUDENT_TEACHER_PREVIEW:'1',STUDENT_TOAPI_BUDGET_CREDITS:'100',THREADS_USER_ACCESS_TOKEN:'THtok',THREADS_USER_ID:'123',UPLOAD_POST_API_KEY:'up-good',EXA_API_KEY:'e',FIRECRAWL_API_KEY:'f',TAVILY_API_KEY:'t'};
const json=(status,body)=>({status,ok:status<300,json:async()=>body});
function fakeFetch(calls){return async(url,init)=>{calls.push({url:String(url),auth:init?.headers?.Authorization||init?.headers?.apikey||''});const u=String(url);
 if(u.includes('/auth/v1/health'))return json(200,{name:'GoTrue'});
 if(u.includes('toapis.com/v1/models'))return init.headers.Authorization==='Bearer sk-good'?json(200,{data:[{id:'a'},{id:'b'}]}):json(401,{error:{message:'bad'}});
 if(u.includes('/v1.0/me'))return json(200,{id:'123',username:'demo'});
 if(u.includes('/debug_token'))return json(200,{data:{scopes:['threads_basic','threads_content_publish']}});
 if(u.includes('/api/uploadposts/users'))return init.headers.Authorization==='Apikey up-good'?json(200,{success:true,profiles:[{username:'p1',social_accounts:{}}]}):json(401,{});
 if(u.includes('tikhub'))return json(200,{code:200,api_key_data:{api_key_name:'k'}});
 throw new Error('unexpected '+u);};}
test('all keys good → READY, values never echoed',async()=>{const calls=[];const r=await checkKeys(GOOD,{fetch:fakeFetch(calls)});
 assert.equal(r.readyForClass,true);assert.equal(r.summary.fail,0);assert.equal(r.summary.missing,0);
 const text=JSON.stringify(r)+formatReport(r);for(const v of ['sk-good','THtok','up-good','sb_publishable_x'])assert.ok(!text.includes(v),'leaked '+v);
 assert.ok(calls.every(c=>!c.url.includes('/generations')&&!c.url.includes('threads_publish')),'must not spend or publish');});
test('wrong THREADS_USER_ID names the real id as the next step',async()=>{const r=await checkKeys({...GOOD,THREADS_USER_ID:'999'},{fetch:fakeFetch([])});
 const t=r.rows.find(x=>x.id==='threads');assert.equal(t.status,'fail');assert.match(t.next,/123/);assert.equal(r.readyForClass,false);});
test('preview flag off, low budget, bad TopAPIs key, TOPAPIS alias',async()=>{const r=await checkKeys({...GOOD,STUDENT_TEACHER_PREVIEW:'',STUDENT_TOAPI_BUDGET_CREDITS:'20',TOAPI_API_KEY:'',TOPAPIS_API_KEY:'sk-alias'},{fetch:fakeFetch([])});
 const by=Object.fromEntries(r.rows.map(x=>[x.id,x]));assert.equal(by.preview.status,'missing');assert.equal(by.budget.status,'fail');assert.equal(by.toapi.status,'missing');assert.match(by.toapi.detail,/少一個 S/);
 const r2=await checkKeys({...GOOD,TOAPI_API_KEY:'sk-bad'},{fetch:fakeFetch([])});assert.equal(r2.rows.find(x=>x.id==='toapi').status,'fail');});
test('Upload-Post missing is skip on free track, missing on pro',async()=>{const env={...GOOD,UPLOAD_POST_API_KEY:''};
 assert.equal((await checkKeys(env,{fetch:fakeFetch([]),track:'free'})).rows.find(x=>x.id==='uploadpost').status,'skip');
 assert.equal((await checkKeys(env,{fetch:fakeFetch([]),track:'pro'})).rows.find(x=>x.id==='uploadpost').status,'missing');
 assert.equal((await checkKeys(env,{fetch:fakeFetch([]),track:'free'})).readyForClass,true,'Upload-Post is not required');});
test('network failure is reported, not thrown',async()=>{const r=await checkKeys(GOOD,{fetch:async()=>{throw Object.assign(new Error('x'),{name:'TimeoutError'});}});
 assert.equal(r.rows.find(x=>x.id==='supabase').status,'fail');assert.match(r.rows.find(x=>x.id==='toapi').detail,/15 秒/);});
test('429 rate limit is not a bad key',async()=>{const f=async(u)=>({status:String(u).includes('supabase')||String(u).includes('/v1.0/me')||String(u).includes('debug_token')?200:429,ok:!String(u).includes('toapis')&&!String(u).includes('upload')&&!String(u).includes('tikhub'),json:async()=>String(u).includes('/v1.0/me')?{id:'123',username:'d'}:String(u).includes('debug')?{data:{scopes:['threads_content_publish']}}:{}});
 const r=await checkKeys({...GOOD,TIKHUB_API_KEY:'tk'},{fetch:f});const by=Object.fromEntries(r.rows.map(x=>[x.id,x]));
 assert.equal(by.toapi.status,'ok');assert.match(by.toapi.detail,/429/);assert.equal(by.uploadpost.status,'ok');assert.equal(by.tikhub.status,'skip');assert.equal(r.readyForClass,true);});
