process.env.STUDENT_TOAPI_BUDGET_CREDITS='20';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {finishImageTask,imageRequest,pollImage,resultUrl,submitImage} from '../lib/toapi-image.mjs';

const brain={brainProfile:{tone:'direct',interests:['AI'],look:{primaryColor:'#08080C',accentColor:'#7C5CFF',fontHeading:'Inter',fontBody:'Inter',watermark:'@demo'}}};
test('image request is fixed to original model contract and brand look',()=>{const body=imageRequest({text:'A useful AI automation idea',visualDirection:'editorial portrait',ratio:'4:5',brain});assert.equal(body.model,'gpt-image-2.5-flare');assert.equal(body.resolution,'1K');assert.equal(body.n,1);assert.match(body.prompt,/#08080C/);assert.match(body.prompt,/@demo/);assert.match(body.prompt,/STYLE REFERENCES: none attached/);assert.throws(()=>imageRequest({text:'short',ratio:'1:1',brain}));});
test('result URL accepts provider result shape and rejects insecure output',()=>{assert.equal(resultUrl({result:{data:[{url:'https://cdn.example.com/a.png'}]}}),'https://cdn.example.com/a.png');assert.throws(()=>resultUrl({data:[{url:'http://unsafe.example/a.png'}]}));});
test('async image task reserves once, polls, and reconciles observed credits',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'student-image-'));let balances=0;const fake=async(url,options={})=>{if(url.endsWith('/balance'))return Response.json({success:true,used_credits:balances++?13.5:10,credits_per_usd:200});if(options.method==='POST')return new Response(JSON.stringify({id:'task_img_abc123',status:'queued',progress:0}),{status:200});return Response.json({id:'task_img_abc123',status:'completed',progress:100,result:{data:[{url:'https://cdn.example.com/a.png'}]}});};try{const body=imageRequest({text:'A useful AI automation idea',ratio:'1:1',brain});const task=await submitImage({requestId:'11111111-1111-4111-8111-111111111111',workspaceId:'ws',body},{dir,key:'secret',fetcher:fake});assert.equal(task.taskId,'task_img_abc123');await assert.rejects(submitImage({requestId:'11111111-1111-4111-8111-111111111111',workspaceId:'ws',body},{dir,key:'secret',fetcher:fake}));const polled=await pollImage(task.taskId,{dir,key:'secret',fetcher:fake});assert.equal(polled.status,'provider-completed');const done=await finishImageTask(task.taskId,{status:'completed',record:{storagePath:'generated/ws/task.png'}},{dir,key:'secret',fetcher:fake});assert.equal(done.observedCredits,3.5);const ledger=JSON.parse(await readFile(path.join(dir,'_toapi-budget.json'),'utf8'));assert.equal(ledger.uncertain,false);assert.equal(ledger.spentCredits,3.5);}finally{await rm(dir,{recursive:true,force:true});}});
