import {NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
import {createHash} from 'node:crypto';
import {cloudRuntime} from '@/lib/cloud-runtime.mjs';
import {connectionConfig} from '@/lib/read-only.mjs';
import {runtimeBrain} from '@/lib/ommi-brain.mjs';
import {imageRequest,resultUrl} from '@/lib/toapi-image.mjs';
import {assertLocalRequest,ContentError} from '@/lib/content-engine.mjs';
import {token} from '@/lib/api';
import {updateQueueRecord} from '@/lib/queue-record.mjs';
import {templatePrompt} from '@/lib/image-template.mjs';
export const dynamic='force-dynamic';export const maxDuration=120;
const headers={'Cache-Control':'no-store'};
const fail=(e:unknown)=>NextResponse.json({error:e instanceof ContentError?e.message:'圖片操作未完成，保留原請求並恢復'},{status:e instanceof ContentError?e.status:503,headers});
function db(auth:string){const c=connectionConfig();return createClient(c.url,c.key,{global:{headers:{Authorization:'Bearer '+auth}},auth:{persistSession:false,autoRefreshToken:false}});}
async function signed(auth:string,path:string){const {data,error}=await db(auth).storage.from('media-images').createSignedUrl(path,3600);if(error||!data?.signedUrl)throw new ContentError('預覽網址未完成，請恢復',502);return data.signedUrl;}
function view(job:any){return {taskId:job.id,providerTaskId:job.providerTaskId,status:job.state==='completed'?'completed':job.state==='failed'?'failed':job.state==='unknown'?'unknown':'in_progress',progress:job.progress||0,error:job.state==='failed'?'圖片供應商回報失敗；沒有重新生成':undefined};}
async function attach(runtime:any,job:any){const target=job.payload.queueTarget;if(!target)return null;try{const draft=await runtime.job(target.id);if(draft.kind!=='text'||draft.state!=='completed')throw new Error('草稿未完成');if(draft.record.images?.[target.platform]?.taskId===job.id)return null;const record=updateQueueRecord(draft.record,{action:'attachImage',platform:target.platform,expectedVersion:target.expectedVersion,verifiedImage:{taskId:job.id,storagePath:job.record.storagePath}});await runtime.update(draft,'completed',{record});return null;}catch{return '圖片已保存，但草稿版本已變或附圖未完成。重新選Queue草稿，再按附圖，唔使重新生圖。';}}
export async function GET(request:Request){try{assertLocalRequest(request);const auth=token(request)!;const runtime=await cloudRuntime(auth);const id=new URL(request.url).searchParams.get('taskId');if(id){const job=await runtime.job(id);if(job.kind!=='image')throw new ContentError('請求類型不符');return NextResponse.json(view(job),{headers});}const items=await runtime.client.imageGenerations(runtime.workspace);return NextResponse.json({items:await Promise.all(items.map(async(item:any)=>({...item,signedUrl:await signed(auth,item.storagePath)}))),budget:await runtime.budget(),pending:await runtime.pendingJobs('image')},{headers});}catch(e){return fail(e);}}
export async function POST(request:Request){let runtime:any,job:any;
 try{assertLocalRequest(request);const auth=token(request)!;runtime=await cloudRuntime(auth);const body=await request.json();const key=process.env.TOAPI_API_KEY;if(!key)throw new ContentError('未配置ToAPI key');
  if(body.action==='resume'){job=await runtime.job(body.taskId);}
  else {const snapshot=await runtime.requireBrand();const brain=runtimeBrain(snapshot,await runtime.client.ommiBrain(runtime.workspace));let template:any;let selectedBrain=brain;if(body.templateId){const rows=await runtime.request('sources?'+new URLSearchParams({select:'metadata',workspace_id:'eq.'+runtime.workspace,source_id:'eq.image-template:'+body.templateId}));template=rows[0]?.metadata;if(!template||template.archived)throw new ContentError('模板不存在或已封存');if(body.brandMode!=='latest')selectedBrain=template.brand;}const payload=imageRequest({text:body.text,visualDirection:body.visualDirection,ratio:body.ratio,brain:selectedBrain});if(template){payload.prompt+='\n'+templatePrompt(template,{text:body.text,focus:template.focus,brand:{owner:selectedBrain.owner,brainProfile:selectedBrain.brainProfile}});}if(body.action==='preview')return NextResponse.json({prompt:payload.prompt,model:payload.model,resolution:'1K',budget:await runtime.budget()},{headers});let queueTarget=null;if(body.queueTarget){const target=await runtime.job(body.queueTarget.id);if(target.kind!=='text'||target.state!=='completed'||!target.record.brief.platforms.includes(body.queueTarget.platform)||target.record.version!==body.queueTarget.expectedVersion)throw new ContentError('Queue草稿已變，請重新讀取',409);queueTarget=body.queueTarget;}const claimed=await runtime.claim(body.requestId,'image',{...payload,queueTarget});job=claimed.job;
   if(claimed.claimed){try{const response=await fetch('https://toapis.com/v1/images/generations',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify(payload),redirect:'error',signal:AbortSignal.timeout(45000)});const raw=(await response.text()).replaceAll(key,'[redacted]');let data:any;try{data=JSON.parse(raw);}catch{data={unparsedResponse:raw.slice(0,12000)};}const id=data.id||data.task_id||data.data?.task_id;const immediate=response.ok?resultUrl(data):null;const valid=typeof id==='string'&&/^[A-Za-z0-9_-]{8,180}$/.test(id);if(!response.ok||(!valid&&!immediate)){job=await runtime.update(job,'unknown',{providerHttpStatus:response.status,providerSubmit:data,error:'提交未取得可追蹤task；保留回應供核對'});throw new ContentError('圖片提交未確認（HTTP '+response.status+'），原回應已保存；不重新付費',502);}job=immediate?await runtime.update(job,'generated',{providerUrl:immediate,providerSubmit:data,providerHttpStatus:response.status}):await runtime.update(job,'generating',{providerTaskId:id,providerSubmit:data,providerHttpStatus:response.status});}
    catch(e){if(job.state!=='unknown'){try{job=await runtime.update(job,'unknown',{error:'提交狀態待核對'});}catch{}}throw e instanceof ContentError?e:new ContentError('圖片提交狀態未知，請核對原請求；不重新付費',502);}
   }
   return NextResponse.json({...view(job),budget:await runtime.budget()},{status:202,headers});
  }
  if(job.kind!=='image')throw new ContentError('請求類型不符');
  if(job.state==='failed')return NextResponse.json(view(job),{headers});
  if(job.state==='completed')return NextResponse.json({attachmentError:await attach(runtime,job),...view(job),...job.record,signedUrl:await signed(auth,job.record.storagePath)},{headers});
  if(!job.providerTaskId&&!job.providerUrl&&job.providerSubmit){const url=resultUrl(job.providerSubmit);if(url)job=await runtime.update(job,'generated',{providerUrl:url});}if(!job.providerTaskId&&!job.providerUrl)throw new ContentError('原請求提交狀態未知，需核對provider；未重新生成',409);
  if(!job.providerUrl){
   const response=await fetch('https://toapis.com/v1/images/generations/'+encodeURIComponent(job.providerTaskId),{headers:{Authorization:'Bearer '+key},redirect:'error',signal:AbortSignal.timeout(20000)});if(!response.ok)throw new ContentError('圖片狀態暫時未能讀取',502);const data=await response.json();
   if(data.status==='failed'){job=await runtime.update(job,'failed',{providerPoll:data,progress:0});return NextResponse.json(view(job),{headers});}
   const url=resultUrl(data);if(data.status!=='completed'||!url)return NextResponse.json({...view(job),progress:Number(data.progress)||0},{headers});
   job=await runtime.update(job,'generated',{providerUrl:url,providerPoll:data,progress:100});
  }
  const response=await fetch(job.providerUrl,{redirect:'error',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new ContentError('已生成，下載暫時失敗；請恢復同一張圖',502);const contentType=response.headers.get('content-type')||'';if(!contentType.startsWith('image/'))throw new ContentError('結果不是圖片');if(Number(response.headers.get('content-length'))>10000000)throw new ContentError('圖片超過10MB');const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.length>10000000)throw new ContentError('圖片超過10MB');
  const storagePath=runtime.workspace+'/generated/'+job.id+'.png';const storage=db(auth).storage.from('media-images');const hash=createHash('sha256').update(bytes).digest('hex');const upload=await storage.upload(storagePath,bytes,{contentType,upsert:false});
  if(upload.error){const previous=await storage.download(storagePath);if(previous.error||!previous.data)throw new ContentError('Storage未完成；請恢復同一張圖',502);if(createHash('sha256').update(new Uint8Array(await previous.data.arrayBuffer())).digest('hex')!==hash)throw new ContentError('Storage同一路徑已有不同內容，未覆寫',409);}
  const record={taskId:job.id,providerTaskId:job.providerTaskId,requestId:job.id,model:job.payload.model,size:job.payload.size,resolution:'1K',prompt:job.payload.prompt,storageBucket:'media-images',storagePath,contentType,bytes:bytes.length,sha256:hash,generatedAt:job.updatedAt,estimatedCredits:3,observedCredits:null,provider:'toapis',storageVerified:true};
  await runtime.client.saveImageGeneration(runtime.workspace,record);job=await runtime.update(job,'completed',{record});return NextResponse.json({attachmentError:await attach(runtime,job),...record,status:'completed',signedUrl:await signed(auth,storagePath)},{headers});
 }catch(e){return NextResponse.json({error:e instanceof ContentError?e.message:'圖片操作未完成，請保留原請求',taskId:job?.id,requestState:job?.state||'not-created'},{status:e instanceof ContentError?e.status:503,headers});}
}
